var data3Ext =[
["Twitter_ID","UserName","Reply", "Share", "Like"],
["evannex_com","EVANNEX for Tesla",461,6381,15366],
["TeslaModel3News","Tesla Model 3 News",422,2878,9876],
["Model3Owners","Model 3 Owners Club",823,1773,9571],
["TeslaPittsburgh","Tesla Pittsburgh",190,635,2118],
["XingleiShen","Xinglei Shen",108,585,2223],
["techeblog","TechEBlog",0,796,759],
["TeslaClubUK","Tesla Owners Club UK",159,611,777],
["omg_tesla","Omg_Tesla",97,306,1128],
["JimHarris","Jim Harris",35,644,764],
["jassummers","Jas Summers",75,220,800],
["ubuygas","UBUYGAS",34,347,510],
["ElectriCarsES","ElectriCars",70,28,714],
["bmwblog","BMWBLOG",24,188,578],
["plugshare","PlugShare",26,152,501],
["Jasonrbirchall","Jason R Birchall",170,96,332],
["AmazingChevVolt","Thomas J. Thias",23,247,287],
["kirillklip","Kirill Klip",9,387,153],
["electro_mov","electromovilidad",26,120,398],
["therealautoblog","Autoblog",21,175,337],
["droeder72","Dirk Röder",44,86,352],
["JWinstonTS","TS Julia Winston",18,54,387],
["TheTeslaModelS","TeslaModelS",4,185,249],
["ChargeMap","ChargeMap",18,171,216],
["crociangelini","Elisabetta",0,182,210],
["PaulHolzapfel","Paul Holzapfel",133,66,168],
["leahyparks","Leah Y Parks",6,187,149],
["melindavermeer","Melinda",48,48,224],
["TamaraMcCleary","Tamara McCleary",0,152,140],
["dlacalle_IA","Daniel Lacalle",18,90,162],
["MITJAKE","Jake Chen",5,57,202],
["yicaichina","Yicai Global 第一财经",0,152,110],
["IEEEorg","IEEE",0,85,170],
["AaronEichinger","Aaron Eichinger",10,20,222],
["emicimaz","Emiliano Mazzetto",12,12,228],
["JasonHartmanROI","Jason Hartman",45,55,150],
["GerberKawasaki","Ross Gerber",20,33,192],
["MotorTrend","Motor Trend",7,35,203],
["c4chaos","~C4Chaos",21,22,188],
["raphaelsebban","Raphael Sebban",0,192,36],
["PluginCarsNews","PluginCars",0,98,126],
["StrategicTechVC","Tech Investor",5,34,169],
["eshellshear","Evan Shellshear",14,72,121],
["TeslaBargain","Tesla Bargain",41,66,98],
["TeslaModelX","Tesla Model X FAN",0,54,136],
["Rexyyy_","Kim",12,34,137],
["EverCharge","EverCharge",0,89,81],
["slcuervo","Saul Lopez ⚡️🔋",7,28,127],
["getmeontop","GetMeOnTop",0,64,88],
["twandroid","FrAndroid 📱⌚️🖥🎮🎧",6,32,108],
["Nikstrade","Nikstrade OÜ",16,80,48],
["findit_social","findit_social",0,143,0],
["evholes","#EVHOLE",14,40,88],
["foroelectricos","ForoCochesEléctricos",14,28,98],
["guidaautonoma","guidaautonoma",1,77,59],
["juhani","Juhani Polkko 🇫🇮",30,0,105],
["baddriversofCA","Nor-Cal Dashcam",0,34,96],
["teslamagazincz","TeslaMagazin.cz",0,65,65],
["EctoFlapjack","C.",0,0,126],
["RealOTCStockGuy","TheRealOTCStockGuy",0,42,84],
["globedrive","Globe Drive",12,60,49],
["AllinOneTesla","AllinOne|Tesla",0,32,88],
["FormulaeTesla","Tesla_FormulaE",0,34,85],
["beebomco","Beebom",8,28,82],
["ChargePointnet","ChargePoint",4,40,72],
["Breezcar_FR","Breezcar",0,55,59],
["evomagazine","evo Magazine",0,20,90],
["foxlider1","#foxlider1",0,50,60],
["jasononsax","Jason Whitmore",22,0,88],
["countryviewkris","Kris Currie",0,18,90],
["Mitch_Fox","Mitch Fox",0,36,72],
["ButenegroEV","butenegro",10,26,71],
["JJODRY","Julien JODRY",0,35,71],
["niallsharkey","niall sharkey",0,0,100],
["jenbeightley","Jennifer Beightley",21,7,70],
["WaitingForTesla","Waiting For Tesla",25,7,65],
["NoShadyLady","Ellen Dux",0,32,64],
["amtvmedia","Christopher Greene",0,24,72],
["JSuaveFrancois","J.Francois",16,0,80],
["BBCStreeter","Susannah Streeter",10,40,44],
["ComOdity_Man","ComOdity_Money_Man",0,36,54],
["automobilemag","Automobile Magazine",0,32,56],
["ID_R_McGregor","Robert McGregor",3,30,54],
["illestJTT","john tran",9,18,57],
["TeslaMS60","Tesla Model S60",1,21,60],
["Inta_Tain","I promote Artist🤘",0,52,26],
["invest2success","Invest2Success.com",0,26,52],
["PeterNemere","Peter Nemere",11,0,66],
["AntilaHeli","Heli Antila",4,0,72],
["alxartdesign","Alex Jaeger",11,3,62],
["James_Galvin","James Galvin",0,13,60],
["republic","Republic",0,21,52],
["breastcar","BreastCar TESLA",0,23,50],
["TeslaSAfrica","Tesla South Africa",36,9,27],
["teslaology","Teslaology",0,16,56],
["ElectricCarNews","Morey Schapira",0,23,48],
["Kristof_1978","Kristof Lambrecht",22,0,49],
["TradeAlvexo","Alvexo Trade",6,18,45],
["TeslaOwnerClub","Everything Tesla",0,7,60],
["tech_prophecy","Tech_Prophecy Inc.",0,22,44],
["Michaeljonair","Michael J On Air",11,22,33],
["maxKeppeler","Maximilian Keppeler",0,0,66],
["bullishbroker24","George Ioakeimidis",16,0,49],
["MapleSquid","Drago",0,16,48],
["evDOTnetwork","EVnetwork",0,32,32],
["mapowing_paul","Paul Ma",12,8,44],
["thetechsledge","TechSledge Official",7,21,35],
["NWMike","Moynihan",0,13,50],
["techjunkiejh","Tech Junkie",0,32,31],
["IT_Times_de","IT-Times.de_IT News",0,18,44],
["LMerchantDesign","Laura Merchant",7,7,46],
["MarinCountyNews","Marin County News",0,15,45],
["MoonshineDesign","Adrienne",0,16,44],
["futurasciences","Futura",0,27,33],
["kalhamaar","El Poulpinou 🐙",10,10,40],
["mrjordonez","José Ordoñez",0,11,47],
["SonjamvanS","Sonja van Staveren",0,19,38],
["Guardian_AAngel","GuardianDroneAngel🛰",12,12,32],
["pimskeks","Nikias Bassen",7,0,49],
["Bespaarenergies","M. de Loos",0,20,36],
["Ochthenoodle","Joanna Wolthuis",0,0,56],
["ani_gooner","Animesh Rawat",0,14,42],
["ryantnt","Tim Ryan",14,0,42],
["MASTERJOEYJEDI","JOE FIGUEROA",14,14,28],
["CanMind","Sameem Monzaviyan",0,0,55],
["shobe","Matt Shobe",9,0,45],
["vitorrindia","vitorr",0,36,18],
["greentechfusion","GreenTechFusion",0,42,12],
["ArtLightstone","Art Lightstone",0,13,39],
["kimpaquette","Kim Paquette",6,0,46],
["teslainventory","Erik",5,3,44],
["javmaher9","Javad Maher",13,13,26],
["TiffanyEngineer","Tiffany - Engineer",0,0,52],
["MarkScarpato","Mark Scarpato",1,1,50],
["ecarshu","e-cars.hu",0,19,32],
["lifeinportugal","portugal",7,14,30],
["ElectricMotorsC","ElectricMotorsClub",0,1,49],
["splendores","Sandro Splendore",6,0,44],
["Stevo10211Steve","Steve Nelson",10,0,40],
["BESTKR_RU","Уникальный Кузовной",0,16,32],
["ZoePionierin","Jana",0,6,42],
["Reeman1979","Ryan McLeod",12,0,36],
["particle_seeker","TrumpIsAScamArtist",0,27,18],
["cochranb","Brian Cochran",0,0,45],
["TeslaEu","@TeslaEu",0,0,45],
["SteveLareau","Steve Lareau",0,18,27],
["TheOther_MJ","Michael Jackson",9,9,27],
["pauleklink","Touchdown Tampa Bay",0,18,27],
["ntrsfrml","M Fresh",0,5,39],
["TrendGizmo","TREND GIZMO",0,35,9],
["TeslaMotorsPT","Tesla Portugal",0,0,44],
["Joel_Duren","Joel Durén",7,7,28],
["roklen24","Roklen24.cz",14,14,14],
["metz123","John Metzger",0,0,42],
["hbkwee","Hwie-Bing Kwee",13,0,29],
["JibberJabCouple","JibberJabCouple",0,14,28],
["Natursun","Philip Ling",35,0,7],
["JeremyGreenlee","Jeremy Greenlee",17,0,25],
["TSportline","T Sportline",0,14,28],
["Scuolaguida_it","Scuolaguida.it",0,0,42],
["sharewithshyam","Shyam",0,21,21],
["2ontrack","Robin",0,14,27],
["PConfidential","Profit Confidential",0,20,20],
["angelperez_1","Ángel Pérez",0,10,30],
["i_Peter","Peter Bering",0,20,20],
["momcloud1","sharon",4,12,24],
["vieiraUAE","Alex Vieira",20,7,13],
["IcemanTrading","ICEMAN",12,8,20],
["chrisamirr","Christian",5,0,35],
["teslasharing","Teslasharing - Bolt",13,27,0],
["nievowners","NI EV Owners",8,8,24],
["HemantChandak","Hemant Chandak",3,15,21],
["donbarbieri","Don Barbieri",10,0,28],
["OnBRM","OnBRM",9,9,18],
["h0uz3","Obstministrator",11,2,23],
["JohnnyKarbin","Johnny Rubin",0,0,36],
["JohnPerlmutter","John Perlmutter",0,24,12],
["EVIncentivesCA","EV Incentives Canada",0,10,25],
["calomas","©hristopher A Lomas",0,28,7],
["RedlionEster","Ester Gjorek",0,7,28],
["iDaveSnow","Dave Snowberger",0,0,34],
["steflesat","Stéphane Bazin",0,6,28],
["robgagnon","Robert Gagnon",0,17,17],
["michaelmacolino","Michael Macolino",4,8,22],
["samrotberg","Sam Rotberg",0,0,33],
["ClaytonTBurrows","Clayton Burrows",0,11,22],
["jenskohnen","Jens Kohnen",22,0,11],
["LargoluvScience","Vedran Largo",0,8,24],
["ManouSchuetz","Manou Schütz",10,11,11],
["MavenAdviser","Andy Hart",8,0,24],
["ArsTechnicaUK","Ars Technica UK",0,22,9],
["TMRnews","The Motor Report",0,15,16],
["jromeul","Juan Romeu",11,0,20],
["Hovscorpion12","Hovscorpion12",2,24,5],
["paulbennett966","Paul Bennett",5,15,10],
["SAEdelstein","Stephen Edelstein",0,0,30],
["lexgravestm","Lex Graves📱📸",10,0,20],
["andreacreativo","Andrea Carini",10,0,20],
["Oscar_3point7","Oscar Romero Jr. ❄️",10,10,10],
["FleetdriveElect","Fleetdrive Electric",5,15,10],
["ToddGeneva","Todd",20,0,10],
["Lieberum_com","Marcus Lieberum",0,0,30],
["ignaciogafo","ignacio gafo",0,10,20],
["NatalkaL","Natalka Lindstrom",0,0,30],
["KorrelZ_NL","KorrelZoutNL",10,0,20],
["Automobile_life","Yoann",0,8,22],
["mikkonou","Mikko M. Nousiainen",13,0,16],
["CCLsaltlake","CCL Salt Lake City",0,18,11],
["dmackdaddy","dmackdaddy",0,0,28],
["MPFRatings","MPF Ratings Limited",0,14,14],
["THESTOCKER","STOCKER",0,12,16],
["sriramaa","Sriram Ramanathan",1,12,15],
["mwt2008","Mark W Tebbutt",12,11,5],
["griffperry","Griffin Perry",2,6,20],
["wook747","Waqas Akbar",8,4,16],
["easychargeme","easycharge.me",1,8,19],
["Truthdig","Truthdig",0,12,15],
["christesla","Chris Danks",18,0,9],
["EconomicHedge","Joseph Jones",18,9,0],
["Dalten_Mitchell","☯",0,9,18],
["Oxford_Life","In Oxford",0,0,27],
["KurtAnglese","Kurt Anglese",0,0,27],
["MotorHeadMama","MotorHead Mama",0,9,18],
["heyimjacooob","undefined is not a",9,9,9],
["aby002","Aby Mathew",0,9,18],
["JEEPTESLABURGER","LEO YANG",13,0,13],
["deborahskyrim","deborah marie",0,13,13],
["JayECrawford","❄️Jay E Crawford❄️",0,0,26],
["ecartestdrives","ecartestdrives.com",0,4,22],
["JesusDulay","Mr. Dulay",13,0,13],
["_MisterBD","Brian D",13,0,13],
["Tesla3Forum","Tesla Model 3 Forum",0,26,0],
["TESLA_AM3","Tesla",6,7,13],
["ElonMuskCritic","NewSpace Critic",0,0,26],
["ms_mims","ms_mims",26,0,0],
["LBS","LondonBusinessSchool",0,12,14],
["BobbyBriggs15","Bobby Briggs",0,0,26],
["mtahirnaeem","Muhammad Tahir Naeem",10,5,10],
["TomVoelk","Tom Voelk",5,5,15],
["rich_teer","Rich Teer",0,0,25],
["nullsetnews","Null Set News",0,12,12],
["TwelfthGear","Twelfth Gear",0,4,20],
["ViewsFromLake","Views From The Lake",0,0,24],
["motorionline","Motorionline.com",0,1,23],
["richardsyeo","Richard Yeo",0,12,12],
["CrippledU","Meta_Mor_Pho_SiS",0,12,12],
["TravelAgentA","AgentA Douglas",8,0,16],
["TyroneStevenson","Tyrone Stevenson",0,0,24],
["UKtechie","UKTechie #BMWi3",10,0,14],
["NacymBaghli","Nacym Baghli",4,8,12],
["AthenaChristod1","Athena Christodoulou",0,8,16],
["HDBolak","Halil Doğan Bolak",0,0,24],
["_cedup_","Ced🌐",16,0,8],
["TimOster","☀️⚡️t⭐️r",0,8,16],
["evsigns","#evSigns",0,8,16],
["johnnydparks","Johnny Parks",0,8,16],
["awildpippin","Katrina",12,0,12],
["Tesla__Roadster","Tesla Roadster FAN",0,24,0],
["fastbuyinc","FastBuy",0,24,0],
["fulvnrg","Alexander Price",0,0,24],
["RichardSylvia17","Richard Sylvia",0,0,24],
["adrianflux","Adrian Flux",12,12,0],
["appcart_us","Find App",0,0,24],
["AutoreviewRu","Авторевю",1,11,11],
["hkdobrev","Haralan Dobrev",0,0,22],
["LegendxDiv","Divya Patel",0,11,11],
["zesty_earth","Zesty Earth News",0,9,13],
["premogroup","PREMO",0,11,11],
["VeliUotila","Veli Uotila",0,0,22],
["BadElectricCar","Sach!",0,11,11],
["AllUnboxed","AllThingsTECH",0,11,11],
["Eccyorkshire","ECCY",0,11,11],
["quattroruote","Quattroruote",0,6,16],
["MeRichEllis","Richard Ellis",11,0,11],
["MiamiVapers","Miami Vapers",11,0,11],
["clareparryjones","Clare Parry-Jones",6,3,12],
["Sound_in_Motion","Sound in Motion",0,0,21],
["imshikhararora","Shikhar Arora",0,7,14],
["XeRiON_TV","XeRiON",0,0,21],
["DavidWelchBN","David Welch",0,4,17],
["xxshadowsn8xx","Kiet Tran Tuan",0,21,0],
["_AlphaStreet","AlphaStreet",0,0,21],
["WiredChuck","Chuck Squatriglia",0,7,14],
["ZenGasai","Zen",0,0,21],
["marbell379","Mark Bell",2,10,8],
["stockmarkettv","stockmarketlive.tv",0,5,15],
["golem","Golem.de",0,9,11],
["CT_78","Chris",4,4,12],
["besser_wisser","Arne Hoem",0,4,16],
["TeslaModelS","Tesla Model S FAN",0,0,20],
["mjordonn","Michael Jordan",10,0,10],
["autodevot","Autodevot",0,9,11],
["organicnz2","Tarlan Isaev",0,0,20],
["pluginamerica","Plug In America",0,10,10],
["SeriousAuto","Serious Autosport",0,10,10],
["afro9strong","Maximus",4,4,12],
["amunkarnak","Amun",0,0,20],
["brad_bischoff","Brad Bischoff",1,3,16],
["cleanenergyorg","SACE",1,11,8],
["ParkingEnergy","ParkingEnergy",2,6,12],
["Lasareath","Sal Cameli",0,5,15],
["SchwarzerThore","Percarx",0,20,0],
["TR132004","Trey Rogers",0,3,17],
["nextvemo","Nextvemo",0,0,19],
["MiddleAgedComet","Comet Tanner",0,0,19],
["kinetic_vision","kinetic vision",1,2,16],
["johnwaines","José Garcia",0,0,19],
["HarrisARoss","Ross Harris",19,0,0],
["hwingo","hwingo",0,13,6],
["Glorfindale","Igor!",0,0,19],
["RonThornton","Ron Thornton",0,14,4],
["JanePitt","Virginia Montanez",3,1,14],
["Urban_Limits","Urban Limits Cycling",0,0,18],
["domkingston","Dominic",9,0,9],
["Greenstartit","Greenstart",0,9,9],
["parthaabosu","Parthaa Bosu",0,6,12],
["JustinModel1988","Justin Antonishek",0,0,18],
["zackyx_","ZackyX",0,0,18],
["techportalntw","The Tech Portal",0,9,9],
["mbevilac","Max Bevilacqua",0,9,9],
["Umit_Paris","Ümit",0,0,18],
["anishadmehta","Anisha Mehta",1,4,13],
["SmartStockNews","SmartStockNews",0,7,11],
["universal_prime","Universal Prime",0,3,15],
["Rafi365","Rafi",0,6,12],
["iris_xyz","iris.xyz",0,9,9],
["atuldaga","atul daga",0,0,18],
["jbook3r","Jeremy Booker",0,18,0],
["BCGinItaly","BCGinItaly",0,12,5],
["marimari_1997","_Mariach_",0,0,17],
["Abhishekhpathak","Abhishekh pathak",0,0,17],
["IBTimesIN_Auto","IBTimes India Auto",1,13,3],
["johnwasik","John F. Wasik",0,15,2],
["AlfiereROSSO","AlfiereROSSO®",0,6,11],
["jyuannkimo","苑舉民",8,0,8],
["spooner_web","just_spoon®",0,0,16],
["greensupercar","Green Supercar",16,0,0],
["CharlotteSoc360","Thomas L. Clark Jr.",0,0,16],
["BorealBikes","Boréal Bikes",0,16,0],
["DonNovaTen","Don Nova",0,8,8],
["drcpaci","chris paci",0,8,8],
["ravi9007","Ravi Bijlani",0,0,16],
["lowrin_de","Jonas",0,0,16],
["LCG_DUDE","Lenin Genao ",16,0,0],
["producermariel","Mariel Myers",6,0,10],
["drivespark","DriveSpark",0,0,16],
["RicardoBlanco","Mr. White",2,1,13],
["Lance_Edelman","Lance Edelman",0,5,11],
["JudahSameth","judah sameth",0,0,16],
["AndreiNeaguCom","Andrei Neagu (Andy)",0,0,16],
["Ken_iam_smith","Ken Smith III",0,0,16],
["energyloadEU","Energyload",0,16,0],
["soporwal","sonila porwal",8,8,0],
["zdre","Andrey Zolotov",0,0,16],
["ErikGroset","Erik Groset 🚀",0,0,16],
["Cryptoplanet1","Cryptoplanet",4,2,10],
["stickycactusink","J.W. Kirby",5,1,10],
["Nathaliedore","Nathalie dore",0,0,16],
["torquenewsauto","Torque News",0,6,9],
["DKOlivier","Olivier D.",0,0,15],
["AppSorbi","Sorbi App",0,10,5],
["Parkkisahko","Parkkisähkö",1,3,11],
["thetorquereport","The Torque Report",0,9,6],
["GreenMotorsDE","Green-Motors.de",0,4,11],
["lymehurts","Artist Naomi McQuade",0,5,10],
["beancounterhank","Jack",0,0,15],
["EkoVozila","EkoVozila.com",0,3,12],
["seddiqs","Seddiq Sebbahi",0,0,15],
["TopGearPh","Top Gear Philippines",0,2,13],
["ziggyfro","Daniel Frohlich",3,3,9],
["hoot_app","Hoot censorfree live",0,0,15],
["marccelus2","Marc Celus",0,0,15],
["jackchenwolf","Jack Chen",3,0,12],
["8btbrs","8bitbros",0,15,0],
["QualitasFinance","Qualitas Finance",0,0,14],
["Alzacz","Alza.cz",0,2,12],
["NerdyPeachVR","Peach VR",0,0,14],
["MusicComposer1","Paul Colmer ☁",0,0,14],
["Briggs713","The Texas Hammer",0,0,14],
["mebritt","Michael Britt",0,0,14],
["kmcginnis1026","Kristin McGinnis",0,0,14],
["j_gers","J G",0,0,14],
["lexiheft","AlexiHoeft",0,0,14],
["iaind76","ID76",0,0,14],
["Imotep95","👌🐸👌Stefan👌🐸👌",0,0,14],
["kirmestechno","Javier Salas",7,0,7],
["SamraWealth","Samra Wealth",0,4,10],
["tactlesstom","Tom",0,7,7],
["nancy_wanda","Nancy Wanda",0,0,14],
["barcycles","Bartosz ",0,0,14],
["GlobalTechHubs","TechHubs",0,0,14],
["MrPeteMorris","Pete Morris",0,14,0],
["sleighingthelaw","Aaron",0,2,12],
["BellJoannaL","Joanna Bell",7,0,7],
["HotHardware","HotHardware",0,8,6],
["Gilchrist_Inc","Michael C. Gilchrist",0,0,14],
["AlexanderDBurch","Alexander D Burch",0,0,14],
["TheGreatBorg","Preben Borg",0,0,14],
["joyeetaaa","joyeeta",0,7,7],
["The_PlugSeeker","The_PlugSeeker",0,1,12],
["ConsenSysKirk","Kirk Dameron",0,13,0],
["JumiaCarGH","Jumia Car Ghana",0,0,13],
["Duoplasmatron","Matthew Coble",0,13,0],
["KimmyRitch","Kim",0,13,0],
["ArrowheadLake","LakeArrowhead.us",0,0,13],
["autoculturemag","Autoculturemag",0,0,13],
["GlamourAffair","Glamour Affair",0,0,13],
["iVaibhavGautam","Vaibhav Gautam",0,0,13],
["AlphSt_Retail","AS Retail",0,9,4],
["bryangirard","Bryan",0,0,13],
["SneakerWonk","Adam, SneakerWonk",3,7,3],
["LearnBonds","LearnBonds.com",0,0,13],
["moe_993","Moe",0,0,13],
["hewett_michael","🇨🇦Michael Hewett",0,0,13],
["YihaoK","King Kong",6,0,6],
["ayush1399","Ayushman Singh",0,0,12],
["Bryr32","Bryan Seely",0,0,12],
["theSPOTapp","SPOT",0,0,12],
["JillGoldworn","Jill Goldworn",6,6,0],
["RichZinom","Rich Moniz",0,0,12],
["idevnull","Swathi Venkatachala",0,4,8],
["SteveBareman","Steve Bareman",6,0,6],
["PrabhakarTheSun","Prabhakar",0,4,8],
["geotaller","geoTaller",0,12,0],
["gangarmihir90","Mihir Gangar",3,3,6],
["lmarchou","Laurent Marchou 🌍",0,8,4],
["StudentOfEarth","Margaret Jones",0,3,9],
["Reezocar_BE","Reezocar_BE",0,0,12],
["321CodyLopez","Cody Lopez",0,0,12],
["UZZETsocial","UZZET",0,4,8],
["G_Frey","Garrett Frey",0,3,9],
["davinalexmma","nivad",0,0,12],
["So_Laureen","Laureen L",0,2,10],
["motoradictos","MotorAdictos",0,6,6],
["Hadi_Syed","Hadi Syed",0,6,6],
["NikDonnelly","Nick",3,0,9],
["judiemiller","Just Judie",6,3,3],
["JonathanBCrabb","Jonathan Crabb",0,0,12],
["vt1coop","Nick Cooper",0,0,12],
["JDBioprimer","Justin Dutra",0,0,12],
["ulsa","Ulrik Sandberg",0,0,12],
["hornetjo","jo caudron",0,12,0],
["COmtnDAD","COmtnDad",0,3,9],
["BrendaGisele69","Gisele",0,0,12],
["NiritiPorwal","niriti porwal",0,6,6],
["jallaphoto","Joseph Allaham",0,0,12],
["edumovlive","EduMovLive",0,0,12],
["Rajinator","Manraj - MSG☺",0,12,0],
["mahoneyjkt","mahoney turnbull 马甜甜",0,0,12],
["lars_H_Hoffmann","Lars H. Hoffmann",11,0,0],
["1370wspd","NEWSRADIO WSPD",0,11,0],
["carolyncaf","Carolyn Caflisch",3,0,8],
["TechBuzzer1","Tech Buzzer",0,0,11],
["Cvr40_","Carlos Carvajal",0,0,11],
["cedric","Cedric Ingrand",1,3,7],
["fobmanny","Manish A. Parikh",0,0,11],
["fuzzynavel910","Fuzzy Navel",0,0,11],
["joeazer","Joe Azer",0,0,11],
["make_it_wayne99","Charles Dick",11,0,0],
["Gr8REALTORinAZ","Joyce Corsi Hazen",0,0,11],
["Wormcam","Dr. Wormy McWormface",0,0,11],
["KingBarksdale","MACHIAVELLI Trained",0,11,0],
["bo_leonard","Alex Leonard",0,0,11],
["arboreous","Kristina Bezanson",11,0,0],
["Jochen_mn","St.M-Gesamtkunstwerk",0,4,7],
["georgiapowerET","Georgia Power ET",2,4,4],
["meinantrieb","Rozalia Jasso",5,0,5],
["William_Qc","Claude Williamson",0,0,10],
["GoldenTalon","Jinho Choi",1,0,9],
["jussiylavaara","Jussi Ylävaara",0,0,10],
["Ren_OckS","Sean Renock",0,0,10],
["mytesladream","My Tesla Dream",0,0,10],
["theTechnoMunch","TechnoMunch",0,5,5],
["GCastevert","Guillaume Castevert",10,0,0],
["suprmotoronline","SuperMotorOnline",0,10,0],
["ItzPrav","≋S≋A≋I≋",2,2,6],
["modernlizbennet","JA",2,0,8],
["MichalDam","Michal Damborsky",5,0,5],
["nickrogilvie","Nick Ogilvie",2,3,5],
["cherylmarquez","Cheryl Marquez",0,0,10],
["BBCKasiaMadera","Kasia Madera",2,1,7],
["roadshow","Roadshow",0,4,6],
["BestStockTrades","Best Stock Trades",0,0,10],
["thibetian","George Achillias",0,2,8],
["Diana_YVR","Diana",10,0,0],
["nhagan97","Nick Hagan",0,0,10],
["4Awesometweet","Optimistic Patriot",2,4,4],
["jimiseadawg","James I Jennings III",0,0,10],
["timsee","Tim Cancila",4,2,4],
["aestusthoughts","Aestus Thoughts",0,0,10],
["MisterGreenEV","MisterGreen EV",0,0,9],
["dannysuges","Danny Suges",9,0,0],
["info73587889","Arthur Lee",0,0,9],
["marquetaxsahara","😈 #marquETasahaRA🔫",0,6,3],
["Bytemarks","Burt Lum",0,0,9],
["lisapowell22","Lisa Powell",0,0,9],
["dsuprnova","Dhruva Suravarapu",0,0,9],
["MalcolmBrooks","Malcolm Brooks",0,0,9],
["MidwestEvolve","Midwest EVOLVE",0,4,5],
["O530CarrisPT","O530 Carris PT",0,0,9],
["premierlease","Mike Mendelsohn",0,9,0],
["ItsJustBongz","GRATEFUL BONGZ",0,0,9],
["Carscoop","Carscoops",0,9,0],
["God2be","Birgit Junker",0,9,0],
["thomashauer_at","Thomas Hauer",0,0,9],
["technewsinc","Tech News Inc",0,0,9],
["TeslaFlying","Tesla Fly",0,1,8],
["muhammadusherif","Sherif",0,0,9],
["JohnAaronRead","John Read",6,0,3],
["ultimaclearly","Ultima",0,0,9],
["iworkinazoo","I work in a zoo",0,0,9],
["mpreziuso","Michele Preziuso",0,0,9],
["Tushar_Goyal","Tushar",0,0,9],
["vegas24702","vegas24702",0,9,0],
["Fgurtas","Ferruh Gurtas",0,0,9],
["FabMDZ","Fabrice MENDEZ",0,8,1],
["tinoseeber","Tino",0,0,9],
["RobertSchafnitz","Robert Schafnitz",9,0,0],
["Kingfluffy","Kingfluffy",9,0,0],
["ansudasa","Ansuman Giri 🌞",0,0,8],
["nick_tune","Nick Tune",4,2,2],
["flosted","florence",0,4,4],
["dusanVemic","Dušan Vemić",0,0,8],
["BrookingsMetro","Brookings Metro",0,5,3],
["robenfarzad","Roben Farzad🐬",0,0,8],
["SpinachBranding","Spinach",0,0,8],
["deepbluecea","Ben Weiss",0,4,4],
["guerreraf72","Francesco Guerrera",4,4,0],
["313_full","Full Name",1,1,6],
["teknikensvarld","Teknikens Värld",8,0,0],
["bobschueren","Bob Schueren",0,2,6],
["raddreportmag","Raddington Report",0,0,8],
["nichola_buckley","Nichola Buckley",0,2,6],
["sofecomIT","SOFECOM",0,2,6],
["quentdal","Quentin",0,0,8],
["CSRatings","Crowdsourced Ratings",0,8,0],
["svantewahlqvist","Svante Wahlqvist",0,0,8],
["SaintRenita","Renita Saint",0,0,8],
["sfchronicle","SFChronicle",0,2,6],
["omerkaradeniz","Ömer F. KARADENIZ",0,4,4],
["diegosoria888","Diego soria",0,3,5],
["Goos3D_IE","Goos3D",0,4,4],
["tesla_model_03","Tesla Model 3",0,0,8],
["AndyStalman","Andy Stalman",0,4,4],
["jaysnjay","Jay Powerholics",0,0,8],
["JUSTlN00","Justin",0,0,8],
["raspityourself","Benedictus Jackson",0,0,8],
["drsports808","drsports",0,0,8],
["lanzretreats","Lanzarote Retreats",0,4,4],
["brunel_de","Brunel",0,8,0],
["GAAElettriche","gruppoacquistoauto",0,4,4],
["AgattonTech","Agatton",8,0,0],
["threadloom","Threadloom",0,0,8],
["Goode_Caleb","Caleb Goode",8,0,0],
["HSchoesel","Henriette Schoesel",0,8,0],
["bestdocumentar","Top Documentary Film",0,4,4],
["configit","Configit",0,0,8],
["dgbrent","David Brent 🇨🇦",0,8,0],
["gchong63","Gordon Chong",2,1,5],
["buju77","Yen-Chia",0,4,4],
["trevormelanson","Trevor Melanson",2,4,2],
["TBSNetworks","TBSnetworks.net",0,0,8],
["rayban123","Ray Ban",0,0,7],
["MichelleSturino","Michelle Sturino",0,0,7],
["kenkenn509","*Uncle K.* 💰🏀",7,0,0],
["Hospodarky","Hospodářské noviny",0,4,3],
["AjzShh","Ajaz Shah",0,7,0],
["iamtechlaw","Eric Everson 🤖",0,0,7],
["Owpoga","Owpoga  #gamestosave",0,0,7],
["CoinkingDe","coinking.de",0,0,7],
["coachglove","Bryan G",0,0,7],
["ECARIO_info","ECARIO_info",0,0,7],
["CIOL_NEWS","CIOL",0,0,7],
["Savvy__Investor","Library Smart Invest",0,0,7],
["DIBintl","The Pilot ✈✈🌍🌍",0,7,0],
["DerGerDenWeb","DerGerDenWeb",0,0,7],
["FAUVELCyrille","Cyrille FAUVEL",0,0,7],
["yvizivy","Matthew",0,6,1],
["demers_chris","Chris Demers",0,0,7],
["RSMUK","RSM UK",0,4,3],
["PYerhot","Paul Yerhot, PT, DPT",0,0,7],
["alisonprejean","Alison Prejean",0,0,7],
["RichardSlikker","Richard Slikker",3,0,3],
["varunparakh89","Varun Parakh",0,0,6],
["darrenlister","Darren Lister",0,0,6],
["DanielMHoltz","Daniel M. Holtz",0,0,6],
["thcyron","Thomas Cyron",3,0,3],
["drivingmzstacey","Stacey Randecker",0,0,6],
["nlp187","nlp187",0,0,6],
["grahamhgreen","Graham Green",0,0,6],
["ashleybridget","Ashley McDonald",0,0,6],
["j3pio","j3pio",0,0,6],
["cmacnee","Cynthia Macnee",0,0,6],
["dkumsie","Dhruv Kumar",3,0,3],
["AnthonySoete","AnthonySoete",3,0,3],
["SeattleTeslaS","GK",0,0,6],
["professorjosh","Josh Murdock",0,0,6],
["ObamaCapital","barack Odrama",0,0,6],
["johnalunil","John Mathew",0,0,6],
["OurRealtorLV","Luis Villacres®",3,0,3],
["Novo_IM","Novo",0,2,4],
["cemeena","Meena C",0,0,6],
["philhochstetler","Phil Hochstetler",0,0,6],
["janetofficial1","Janet Scott",0,4,2],
["phertto","Petteri Hertto",0,3,3],
["booker_mail","Booker Mail",0,3,3],
["mariuscbrits","Marius Brits",0,3,3],
["RobinLiong","Robin Liong",2,2,2],
["Amber_and_Onyx","Amber and Onyx",0,0,6],
["back2oblivion","Hi My Name Is Josh",0,0,6],
["UpToDigital","Up To Digital",0,2,4],
["malkabethwendy","Malka Beth Wendy",0,0,6],
["d0cdave","David Sell",0,0,6],
["tinamirtha","Tina Amirtha",6,0,0],
["anbrambilla","Andrea Brambilla",0,3,3],
["rebzvalli","rebecca valli",0,6,0],
["launay_d","launay david",0,0,6],
["LaurenKattuah","Lauren",0,0,6],
["FreshDialogues","Alison van Diggelen",0,0,6],
["A13Frank","Alexander Frank",0,0,6],
["philround","Phil Round",1,2,3],
["SabrinaNgai","Sabrina Ngai",2,0,4],
["eeempf","Ali Abdallah 🌴",0,0,6],
["ctricot","Christophe Tricot",0,4,2],
["teslaverleihde","tesla_verleih_de",0,0,6],
["PinguinoWeb","Pinguino Mag",0,3,3],
["Sherrell_Dorsey","Sherrell Dorsey",0,0,6],
["Motor1Spain","Motor1 España",1,2,2],
["macman222","Secretman",2,0,3],
["AmareshR7","Amaresh Rajaratnam",0,0,5],
["lmeyler","Laurence Meyler",0,0,5],
["BillHuntBits","Bill Hunt",0,1,4],
["ManaYgn","Mana Ygn",0,0,5],
["KickAsthme","KickAsthme",1,0,4],
["ybcap","Yellow Brick Group",0,1,4],
["Wort_FR","Luxemburger Wort FR",0,0,5],
["NollyPrott","Gordon Pye",0,0,5],
["tyler_warnecke","Tyler Jon Warnecke",0,2,3],
["TrippinPippin12","Tammy Taylor",0,2,3],
["autodatoweb","autodato",0,1,4],
["mcnallyd","David McNally",0,2,3],
["Alper76","Alper Gökcan",0,3,2],
["cesantiago_","Carlos E. Santiago",0,0,5],
["JRiedmueller","JRiedmüller",0,1,4],
["Model3andMe","Model3andMe",0,2,3],
["GetNewsd","Newsd",0,5,0],
["ShitikovVanya","Ваня Шитиков",0,0,5],
["TopGearRussia","Top Gear",0,0,5],
["SixthgearIndia","Sixthgear.co.in",0,0,5],
["werthstein","Werthstein",0,0,5],
["ekettoz","Tom Pennings",0,5,0],
["protectorelite","Dominic Licavoli",0,0,5],
["alex_pazhyn","ᴏʟᴇᴋsᴀɴᴅʀ ᴘᴀᴢʜʏɴ ⚡️",0,0,5],
["phonandroid","Phonandroid 🤖📱📰⚡",0,2,3],
["DonBohls","Don Bohls",0,3,2],
["headgearIO","ĤΞADGΞΛΓ",0,1,4],
["jeffkagan","Jeff Kagan",0,0,5],
["boilermkr01","boilermkr",5,0,0],
["cleanenergycan","Clean Energy Canada",0,3,2],
["AnthonyGlomski","Anthony Glomski",0,1,4],
["NederlandMerijn","merijn 🐰",0,2,2],
["DriveElectricUK","DriveElectric",0,1,3],
["UniondeMorelos","La Unión de Morelos",0,2,2],
["RJHartFelt","Richard Jonathan",0,0,4],
["LorenJEdwards","Loren Edwards",0,0,4],
["mediatelecomtec","Mediatelecom Tech",2,0,2],
["LifeInRoseville","America-2017",0,0,4],
["VereraNL","Raymond Vermaas",0,0,4],
["Tazforte1","TazForte jetsons🚀👽",0,2,2],
["EarlBanning","Earl Banning",0,0,4],
["DerpolitArm","Der politische Arm.",0,4,0],
["TheSphereTV","The Sphere Network",0,2,2],
["CBLTInc","CBLT Inc.",0,4,0],
["News18Tech","News18 Tech",0,2,2],
["RichGayton","Rich Gayton",0,2,2],
["PeppePuleo80","Giuseppe Puleo",0,4,0],
["AndyBaldauf","André Baldauf",0,0,4],
["MeekMorano","Michael Romano",2,1,1],
["95octanecom","95octanecom",4,0,0],
["architectsideas","Architectures ideas",0,1,3],
["apostoleez","Apostolis Lianos",0,0,4],
["TimesandTech","Times and Tech",0,4,0],
["TonyMichael","Tony Michael",0,0,4],
["jjctrade","James Cook",0,0,4],
["samqur","Sameer Qureshi",0,2,2],
["cashch","cash",0,2,2],
["lyndonwong","Lyndon Wong",0,0,4],
["theGMIC","GMIC",0,2,2],
["edgyloner","John Napolitano",0,0,4],
["jphillipsmith00","Jason Smith",0,0,4],
["shootersix","Fearless Spectator",0,4,0],
["TheoJans1","Theo Jans",0,2,2],
["alberkhoury24","Alber Khoury",0,0,4],
["kundunnaochan","Emilio Rodriguez",0,0,4],
["FlorasWagon","Flora's Wagon",0,0,4],
["sigspin64","Michael Rescigno",0,1,3],
["ev_match","EVMatch",0,4,0],
["peak_PPR","PeakPerformance(PPR)",4,0,0],
["Carrillomotive","Carrillo'sAutomotive",4,0,0],
["adrianaeloca","Adriana",0,3,1],
["Project4GOOD","Project4GOOD",0,2,2],
["BluePlanetFound","BluePlanetFoundation",0,1,3],
["msch83at","M. Schuster",0,4,0],
["goorha","Prateek Goorha",0,4,0],
["Ron_ElbizzYE","Ron ElbizzYE",2,0,2],
["WorldNewsWow","New World WoW",0,0,4],
["claudiomkd","Claudio M. Camacho 🐧",1,1,2],
["MiCochelectrico","Mi Coche Eléctrico",0,1,3],
["LeNouvelEco","Le Nouvel Economiste",1,1,2],
["stephanieegiron","Stephanie",1,0,3],
["CarsUK","Cars UK",0,3,1],
["DrSanjayPSahoo","Dr. Sanjay Prakash S",2,0,2],
["The_Parkway","M. J. Park Jr.",0,0,4],
["tom_knl","Tk",4,0,0],
["NCEOfficial","Newport Convertible",0,4,0],
["ECraiger","Craig E",4,0,0],
["RubinoJC","Joe Rubino",0,4,0],
["JeffCotrupe","Jeff Cotrupe",2,0,2],
["ukcakeaholics","cakeaholics",0,0,4],
["AjaySankarNair","Ajay Sankar Nair",0,0,4],
["shivanui","Shawn",1,2,1],
["RMPerkinson","Randall Perkinson",1,0,3],
["Highmotor","Highmotor",0,2,2],
["ArMagazin","ARmagazin",0,2,2],
["sachinofgoa","Sachin Raghunathan",0,0,4],
["nicholasmctsang","Nick T ⛅",0,0,4],
["kielaarstad","kiel A",2,0,2],
["cars45ng","Cars45",0,2,2],
["toddakruse","Todd Kruse",0,0,4],
["Kendricksports","Mark Kendrick",0,0,4],
["Palmdale_Motors","PalmdaleMotors",0,0,3],
["Joseph_Solin","Joseph S. Solin",0,1,2],
["jovanik21","Nik Jovanovic",1,0,2],
["JakeSunding","BFF",1,0,2],
["PumpTheJuice","Jay A. Breen",0,1,2],
["_Mickalick","Kevin Mihalich",1,0,2],
["whoisvaibhav","Vaibhav Gadodia",0,0,3],
["DouglasLieblein","D. Danger Lieblein",0,0,3],
["JustinTweets4","Justin S.",1,0,2],
["electricautoguy","ElectricAutoGuy.com",0,1,2],
["RichC","Rich Corbett 🇺🇸",0,0,3],
["im_CParmar","Chirag Parmar",0,0,3],
["tpietrocola","Tony Pietrocola",0,0,3],
["stiendre","Tiendrebeogo Soul",0,0,3],
["silicontalent","Silicon Talent",0,3,0],
["24wheel_news","24wheel_news",1,0,2],
["Chris647Sold","Chris Freeman",0,0,3],
["Tesla_spain","All Electric Car",0,1,2],
["ArnaudDurantin","Arnaud Durantin",0,0,3],
["YahooFinanceCA","Yahoo Canada Finance",0,0,3],
["SingularityArch","Singularity Archive",0,0,3],
["sbuiii","SUNNYBUI©",0,0,3],
["pwassel","Peter Wassel",0,0,3],
["IzoldaT","Izolda Trakhtenberg",0,3,0],
["rutaruta","Ruta Lauciene",0,3,0],
["Redroadmaster","Paul Ebeling",0,0,3],
["hacerboz_imd","Hacer Bozkurt",0,0,3],
["JordannDeMMott","Jordan",3,0,0],
["VigilantGem22","Birdy Bird",0,0,3],
["limpidlogic","Limpid Logic",0,0,3],
["Check123Sci","Check123 SciSpace",0,0,3],
["scvetojevic","Saša Cvetojević",0,0,3],
["Cochemundial","Javi",0,1,2],
["JouriTTiruoJ","JouriT",0,0,3],
["Ajmalzahir98","Ajmal Zahir",3,0,0],
["MikeKollin","Mike Kollin",0,0,3],
["JKgudapati","Jayakrishna Gudapati",3,0,0],
["calisurf","Andy Wasklewicz",3,0,0],
["TimKelleherCorp","Tim Kelleher",1,0,2],
["vallumsoftware","Vallum Software",0,0,3],
["winsusie123","Dr. Susanne Roeder",0,0,3],
["LeadasLOVE","Lead as Love",0,0,3],
["HorMarian","Hornjak Marian",0,0,3],
["honeycreambaba","Matteo Accornero",0,1,2],
["uper_start","Start-Uper",0,1,2],
["CenterpriseInt","Centerprise",0,3,0],
["TheBAM27","Brandon Mckenzie",0,0,3],
["strix1","strix1",0,0,3],
["Plexform","Plexform",0,1,2],
["IncBrainstorm","Brainstorm Inc.",0,0,3],
["aaronmfisher","Aaron M Fisher",0,0,3],
["sberkhoff","Stephan Berkhoff",0,1,2],
["maxwood","Max Wood",0,0,3],
["techtagDE","techtag.de",0,2,1],
["hardwarezone","HardwareZone",0,2,1],
["TheLegitSigg","Branden Sigg",0,0,3],
["FoxNewsLive","Fox News Originals",0,0,3],
["theroadelectric","ev",0,0,3],
["Middletownpress","The Middletown Press",0,1,2],
["jeremybloom","Jeremy Bloom",0,0,2],
["DineshKumaranK","Dinesh Kumaran K",0,1,1],
["DarwinRulz","DarwinRulz",1,0,1],
["misuraolio","A Misura D'Olio",0,2,0],
["QuinnSanders","Quinn Sanders",0,0,2],
["IcepatID","Trillsam Patrick",0,0,2],
["Tradersolution","Trader Solution",0,1,1],
["johhnnyyv","Johnny V",1,0,1],
["mvollmer1","Dr. Marcell Vollmer",0,1,1],
["GhostofCMGI","GhostofCMGI",0,0,2],
["UpdatesJunction","Updates Junction",0,1,1],
["ians_india","IANS Tweets",0,1,1],
["ARULtd","Arafura Resources",0,0,2],
["Nagleess","Nagleess",0,2,0],
["KonTheTweeter","Kon",2,0,0],
["Oliver_Gammell","Oliver Gammell",0,0,2],
["chrisgrey101","Chris Greyling",0,0,2],
["tolyshilman","Toly Shilman",0,1,1],
["RichBrooks350","Richard Brooks",0,1,1],
["BrownBaggsman","Brown baggsman",2,0,0],
["_Netaji","Country First 🇮🇳",0,1,1],
["peterfredman","Peter Fredman",0,1,1],
["Jeres_Rant","Tell It Like It Is!",0,0,2],
["Javi_Coello","Javier Coello",0,1,1],
["RobynNola","Robyn Nola",0,0,2],
["prasann_pandya","Prasann Pandya",0,0,2],
["pabloberbell","pablo bellissimo",0,0,2],
["shiftourpower","Rob Sargent",0,0,2],
["EmilyEtoile1","Emily Etoile",0,1,1],
["Pochutleco","Tito",2,0,0],
["Sonari","Sonari",0,0,2],
["xmetal","Paul Carpenter",0,0,2],
["got2bamerica","GottaloveUSA",2,0,0],
["iKarmik","Karmik Varma",0,2,0],
["bouncing_belly","BouncingBelly",0,1,1],
["NuummiteDxb","Nuummite Consulting",0,0,2],
["Abraham04263808","Abraham Abbas",0,0,2],
["appleofreak","aaklit taneja",0,0,2],
["ChargeEvplus","Charge EV plus",0,0,2],
["tomkarren","Tom Karren",0,0,2],
["BlueSeychelles","Blue Economy",0,0,2],
["fivechapman","Scott Chapman",0,2,0],
["stevemdixon","Steve Dixon",0,0,2],
["videowatchr","Video Watchr",0,0,2],
["Writerpreneur","Writerpreneur",2,0,0],
["redheadheron","Diane herron",0,0,2],
["AkinSawyerr","Akin Sawyerr",0,1,1],
["jsaldi2000","Jorge Saldaña Alegre",0,2,0],
["zoharfisher","Zohar Fisher",0,0,2],
["iadivashi","Human Being",0,0,2],
["__reece97","Reece Recillas",0,0,2],
["abraham_ruiz83","Abraham Ruiz",0,0,2],
["hyttfors","Stefan Hyttfors",0,0,2],
["albertmm88","Albert Morales",2,0,0],
["AliceBowdy","Alice Bowdery",0,0,2],
["TMCJUSTSAIDIT","MACISBACK 🇦🇺",0,2,0],
["stellar_finance","StellarFinance",0,0,2],
["NapaWineGal","Rebecca Martin",0,0,2],
["techupbeat","Tech Upbeat",0,0,2],
["ChargePointAU","ChargePoint Pty Ltd",0,0,2],
["JackPoustrax","Jack Poustraques",1,0,1],
["benedictorchard","Benedict Orchard",0,1,1],
["louispatler","Louis Patler",2,0,0],
["VeronikaCiccone","🗝📿🛡",0,0,2],
["AlexChalekian","Alex Chalekian, CEP®",0,0,2],
["phil_gorski","Phil Gorski",0,0,2],
["Lake_Avenue","Lake Ave Financial",0,0,2],
["MrPapadakis","Dimitris Papadakis",0,1,1],
["AndrewGregoryMN","Andrew Gregory",0,0,2],
["pradster","Pradyut Bafna",2,0,0],
["GS77allgood","Grant Spurrier",0,0,2],
["EffinEffEffEff","PizzaBeerMe&Pop",1,0,1],
["24x7motors","motors24x7",0,0,2],
["azzuri_rk","Azzuri",0,0,2],
["cronociclope","Oscar S. Santisteban",0,0,2],
["rbk_unlimited","Ace Rbk",2,0,0],
["RussHogarth","Russell Hogarth",0,1,1],
["Arsenalcentric","MrKayWilly",0,0,2],
["FredRudondy","Frédéric Rudondy",0,2,0],
["gabros20","Tamas Gabor",0,0,2],
["GeekInfoNow","Bert Fentress",0,0,2],
["LeeSumD32","David L Sumner",0,0,2],
["SumitAltus","Sumit ACII",0,0,2],
["Josepbolart","Josep Bolart",0,0,2],
["ryanbillingham","Ryan Billingham",0,0,2],
["KunleTCampbell","Kunle Campbell ⚡️",0,0,2],
["hickey_gareth","Gareth Hickey",0,0,2],
["PSaundry","Peter Saundry",0,0,2],
["toniamcdonald","Tonia McDonald",0,0,2],
["speedluxcom","SpeedLux",0,0,2],
["koop1980","Maarten Maris",0,0,2],
["JKatzaman","Jim Katzaman",2,0,0],
["erikmattsson","Erik Mattsson",0,0,2],
["ShearComfort","ShearComfort",0,1,1],
["DonSoutherton","Don Southerton",0,0,2],
["ShunShul","Alirezaa",0,0,2],
["whizabz","Abhimanyu Sirothia",2,0,0],
["obseco","Oscar Blanco",0,0,2],
["MrJeremyCrocker","Jeremy Crocker",0,1,1],
["LongendykeL","Lindsey Longendyke",0,0,2],
["1BlogToysTech","#1Blog",0,1,1],
["MMotorSales","Mountville Motors",0,1,1],
["MelanieCandas","Mélanie Candas",0,0,2],
["hayestech01","Matt Hayes",0,0,2],
["Xtechnews","Xtechnews",0,1,1],
["techie_wheels","TechieWheels",0,0,2],
["EloElwell","Elo Vaughn Elwell",0,0,2],
["jakscholes","Jake Scholes",1,0,1],
["JairoArango_CA","Jairo Arango",0,0,2],
["nishchayon","Nishchay Singh",0,0,2],
["cankirmiz","Can",0,0,2],
["monica_mtg","monica g",0,0,2],
["david_covic","David Čović",2,0,0],
["nicolbolaselder","swampdragon",0,1,1],
["DavidAharoni","David Aharoni",0,0,2],
["grupoemopa","EMOPA",0,0,2],
["mattworona","Matt Worona",2,0,0],
["LuningYe","Luning",1,0,1],
["justindillon","justindillon",0,1,1],
["bahree","Amit Bahree",0,0,2],
["depondicchello","H&M",1,0,1],
["ben_hulett","Benjamin Hulett",0,1,1],
["MrJamesAHughes","James Hughes",0,0,2],
["iafricaMotoring","iafrica Motoring",0,1,0],
["markimola","Mark Imola",0,0,1],
["konektinc","Konekt",0,0,1],
["ispeak2u","Paul Alfred",0,0,1],
["Automania_GT","AUTOMANIA",0,0,1],
["TruRockLover","Kat&Prince",0,0,1],
["DavidHorneman","David Horneman",0,0,1],
["WNCN","WNCN",0,0,1],
["Abstract_Ocean","Abstract Ocean",0,0,1],
["gamecockbowling","MrH",0,0,1],
["htsbaldwin","Howard Baldwin",1,0,0],
["DaredareMotus1","jéjé",0,0,1],
["FinancialXpress","Financial Express",0,1,0],
["Albawaba","البوابة",0,1,0],
["MisterB11161930","Mister B R",0,1,0],
["alphr_es","alphr.es",0,1,0],
["erdondraper","ErDonDraper",0,0,1],
["HajiOsbourne","Haji Osbourne",0,1,0],
["gajorock","Gail Jones",0,0,1],
["CKonstanzer","Christian Konstanzer",0,0,1],
["michaelknorris","Mike",0,0,1],
["michaelandreas","Michael Andreas",0,1,0],
["ange1914","Angélique",0,0,1],
["PatrickRuelke","Patrick Rülke",0,0,1],
["kumarayyagari","Kumar Ayyagari",0,0,1],
["BobySPutra","BOBYMBOB",0,0,1],
["DeCoo17","DeCoo",0,0,1],
["mohhzg","Mohammad HZG",0,0,1],
["erwinbruinink","Erwin Bruinink",0,1,0],
["maxinjapan","Massimiliano Zecca",0,0,1],
["_annieross_","Annie Ross",0,0,1],
["JulienLamadon","Julien Lamadon",0,0,1],
["fjmaclennan","Fraser Maclennan",0,0,1],
["LadyRaynbow","Paris Tirone",0,0,1],
["amyrightside","amy",0,0,1],
["jjeffrin","Jeffrin J",0,0,1],
["GROJASNY","Gustavo Rojas",0,0,1],
["montken","Ken Montgomery",0,0,1],
["surgicalrec","Muhammad Mono",0,0,1],
["_reflexe_","_reflexe_",0,1,0],
["ItsEdBall","Ed Ball",0,0,1],
["ApMik","Aploe Miktona",0,0,1],
["asithaangammana","Asitha Angammana",0,0,1],
["dksingh27","Dinesh K Singh",0,0,1],
["jatin1230","Jatin Garg",0,0,1],
["nikolaa_stark","Visakan Balaji",0,0,1],
["DigtlAssetCoach","Bradley C Hughes",0,0,1],
["lisajcb1","Lisa Jacob",0,0,1],
["AnishaKanjilal","Anisha Kanjilal",0,0,1],
["SoneparLab","SoneparLab",0,0,1],
["MainGeeze","TheGeeze.com",0,1,0],
["SSVHD","Jeff Regan",0,0,1],
["sriasis","Wendy",0,0,1],
["Rzewuski_P","Rzewuski",0,0,1],
["paggianilis","Paggiani",0,0,1],
["harryscheinme","harryschein.me",0,1,0],
["247Techie_in","247techie",0,0,1],
["Percentil95","Percentil",1,0,0],
["MediYoga_ax","Daniel Flöjt",0,0,1],
["vinylzone","TSLAZone",0,0,1],
["DanielScherrer","Daniel Scherrer",0,0,1],
["ehuna","ehuna",0,0,1],
["BradPotts","Bradley J Potts",0,0,1],
["Americas1stNews","AFN",0,1,0],
["ICCLMindLadder","Mogens Jensen, Ph.D.",0,0,1],
["VeeFergie","Val Ferguson",0,0,1],
["biaohs23","Shoaib Khan",0,0,1],
["lodeblomme","Lode Blomme",0,0,1],
["HutchSriLanka","Hutch Sri Lanka",0,0,1],
["KrishnaBPrasad","Krishna Prasad",0,0,1],
["nbanthia","Nemy Banthia",0,0,1],
["cityZenflagNews","Laurence d'Assinie",0,1,0],
["jlfoltyn","Jacque Lynn Foltyn",0,0,1],
["GXGroup","GX Group",0,0,1],
["DigikalaMag","Digikala Mag",0,0,1],
["HCdines","HC Dines",0,0,1],
["ThePlushCompany","PLUSH",0,0,1],
["Michael_Kunz","Michael Kunz",0,0,1],
["_FULCH","_🏆_🏆_🏆_🏆_🏆_",1,0,0],
["bidam_II","yashim",0,0,1],
["rholopes","RHÔ",0,1,0],
["fionahyli","Fiona Hy Li",0,0,1],
["codebyts","Acquate",0,0,1],
["jgb6791","Jgb6791",0,0,1],
["FernlundFredrik","Fredrik Fernlund",0,0,1],
["PeninsulaQatar","The Peninsula",0,0,1],
["akmanvell","Anna Johnston",0,0,1],
["lancehomer","Lance Homer",0,0,1],
["TheGameMatTeam","TheGameMatTeam",0,0,1],
["mhtclkz","Mehmet Erkan Çilkız",0,0,1],
["drgonzo777","AC000000",1,0,0],
["DriverlessNow","Driverless Now",0,0,1],
["JHildenMinton","James Hilden-Minton",0,0,1],
["ITP_English","ITP.Net",0,0,1],
["taketwo","Take Two",0,0,1],
["mccormic_tamara","Tamara McCormic",0,0,1],
["intevac_inc","@Intevac_Inc",0,0,1],
["TechSpot","TechSpot",0,0,1],
["robotec","ROBOTEC",0,0,1],
["mr_purelycloud","Christopher Wing",0,0,1],
["LanaCrnjac","Lana Crnjac",0,0,1],
["QuentinLandau","Quentin Landau",0,0,1],
["ekonominotu","Ekonominotu",0,0,1],
["DNikolovskiMBA","D.Nikolovski,BSc.MBA",0,0,1],
["torijelinek","Victoria Jelinek",0,0,1],
["MiasinIsakura","Miasin Isakura",0,0,1],
["kashyap7795","Aakash Kashyap",0,0,1],
["rmawaters","Rob Waters",0,0,1],
["this_orwellian","Joe Biden",1,0,0],
["TomasTyner","Tomás Tyner",0,0,1],
["LatinRisk","LatinRisk Argentina",0,1,0],
["adsynergy","adsynergy",0,0,1],
["WesHellyar","Wes Hellyar",0,0,1],
["A3vdBerg","Adri van den Berg",1,0,0],
["sowheelsindia","sowheels",0,0,1],
["jasongewirtz","Jason Gewirtz",0,0,1],
["masterofdisrupt","Firms Kanayo",0,1,0],
["Nakashon","Asaf Nakash",0,0,1],
["Hellacious_K","Hellacious K",0,0,1],
["Donamezdotcom","Donamez",0,1,0],
["XORDataRecovery","XOR Data Recovery",1,0,0],
["djMaryjane","Maryjane Mixtapes",0,0,0],
["SuhaylJobsity","Suhayl",0,0,0],
["Jjprusk","Joe Pruskowski",0,0,0],
["BrittMJ4evr","Brittany Jean",0,0,0],
["mschipperheyn","Marc",0,0,0],
["Zelig880","Mr_SC",0,0,0],
["timcolicchio","Timothy Colicchio",0,0,0],
["MCSports7","Matt Couden Sports",0,0,0],
["RaienDrops","Raiendr💧ps",0,0,0],
["MarkoSuprun","Marko Suprun",0,0,0],
["MichaelPeshkam","Michael Peshkam",0,0,0],
["iGeoResearch","iGeoResearch",0,0,0],
["Pitanity","Maria Marquez",0,0,0],
["DHQLounge","Digital HeadQuaters",0,0,0],
["Linguste_LS","Linguste L. S.",0,0,0],
["DMPicone","Derek",0,0,0],
["swiv2010","Will Bradbury",0,0,0],
["vaisakh_vg","Vaisakh Venugopal",0,0,0],
["SonderHD","Sonder",0,0,0],
["VipTeslaExp","VipTeslaExperience",0,0,0],
["COURTNEYCOMMERC","CourtneyCommercial",0,0,0],
["auckland2000","Hayden So",0,0,0],
["bee23_t","bee_t",0,0,0],
["Top_Cars1","Chaesar Ali",0,0,0],
["ddbEntertain","ddb Entertainment",0,0,0],
["TcWashington3","Thomas Washington",0,0,0],
["AutoTribute","AutoTribute",0,0,0],
["mo_pmp","Mamoru Mo Fujinoki",0,0,0],
["_Ale_Rizzo_","Alessandro Rizzo",0,0,0],
["InnoArchitect","Doug Collins",0,0,0],
["ThePhoneMantra","*Phone Mantra*",0,0,0],
["cpnStarkiller","Captain Starkiller",0,0,0],
["Josemd","Josemd",0,0,0],
["digital_nic","nicolas 📲",0,0,0],
["maribelis","Maribelis",0,0,0],
["GrupoMundomovil","Grupo Mundomovil",0,0,0],
["sasith_perera","Sasith Perera",0,0,0],
["odave47","Ray Stanz",0,0,0],
["wbikker","Willem Bikker ",0,0,0],
["VinaySanjekar","Vinay Sanjekar",0,0,0],
["BigFishRealtor","chad everts",0,0,0],
["ChrisShawTheMan","Chris",0,0,0],
["jayachandransam","Jayachandran",0,0,0],
["WSJPodcasts","WSJ Podcasts",0,0,0],
["tommauriello","tom mauriello",0,0,0],
["iamRobGregory","Rob Gregory",0,0,0],
["unInstantEpoque","julie peters",0,0,0],
["motorworldindia","Motor World India",0,0,0],
["amcfarla","AJM",0,0,0],
["satyakisays","Satyaki Biswas",0,0,0],
["LatestComments","Latest Commentary",0,0,0],
["Androlizer","Android Trending",0,0,0],
["xRUSSKIx","Patrick Nicholson",0,0,0],
["artemisgirl6","Diana",0,0,0],
["rccfbuzzkill24","Buzzy",0,0,0],
["auto_schmidt","Matthias Schmidt",0,0,0],
["CarNotaFridge","Todd Bianco",0,0,0],
["JoinfoEng","Joinfo Com",0,0,0],
["JohnFunkwaggon","John Bowen",0,0,0],
["FC3BreakinKnees","🚀",0,0,0],
["theprestigebih","The Prestige BiH",0,0,0],
["PDugua","Pierre-Yves Dugua",0,0,0],
["Emmaknickles","Bakayoooooooooooooko",0,0,0],
["wintonsauto","Wintonsworld",0,0,0],
["alessandrossi","Alessandro Rossi",0,0,0],
["Alex_Kump","Alex Kump",0,0,0],
["rnobx","Arnaud Burger",0,0,0],
["NYgermanpress","newyorkgermanpress",0,0,0],
["hubiq","Eduard Huber",0,0,0],
["MaciekGasienica","Maciek Gasienica",0,0,0],
["joequartarone","Joe Quartarone",0,0,0],
["StarrGabe","GStarr",0,0,0],
["HarryUSA1776","harryusa1776",0,0,0],
["DigitalMirko","Mirko Cukich",0,0,0],
["michaeldifebo","Michael D. Di Febo",0,0,0],
["enricovincenzo","Enrico Vincenzo",0,0,0],
["PuckerinR","#DTJrIsFredoCorleone",0,0,0],
["gursimran","Gursimran",0,0,0],
["Crabbtales","Simmo",0,0,0],
["jasonrials","Jason Rials",0,0,0],
["letfreedomreign","Fadia Faraj",0,0,0],
["tonamedina","Tona M.",0,0,0],
["KavindraNadun","Nadun Kavindra",0,0,0],
["robertmarere","Robert Marere",0,0,0],
["KoldoMac","Koldo Duarte ",0,0,0],
["Tangent_McF","Tangent",0,0,0],
["olivierfroggy","Olivier Miss",0,0,0],
["KiranAdhikariEr","Kiran Adhikari",0,0,0],
["johnkoetsier","John Koetsier",0,0,0],
["Junho_K15","Hugo Silva",0,0,0],
["AlyMcF","Aly McF",0,0,0],
["paymentschadder","Chad Alberda",0,0,0],
["porchista","porchista",0,0,0],
["niki_kopp","Niki Kopp",0,0,0],
["anthony9843","Anthony L.",0,0,0],
["Paolo_Pio","Paolo Pio",0,0,0],
["Feed_Fevers","FeedFevers",0,0,0],
["optistrong","optistrong",0,0,0],
["AlertingMainSt","Joshua",0,0,0],
["hyclusivecar","Stormy Meis",0,0,0],
["DeathMetalMods","DeathMetalMods",0,0,0],
["onecrazychief","Fire Chief",0,0,0],
["KnowYourLeaks","KnowYourLeaks",0,0,0],
["akashyssboddeda","Akash YSS Boddeda",0,0,0],
["abbywooden","Abby Tohline Wooden",0,0,0],
["hypercarnation","Miroslava Krause",0,0,0],
["edyafonsogirao","Edy A. Girao",0,0,0],
["mplande","Petter/Maria Lande",0,0,0],
["whyskp","Krishna Prasad",0,0,0],
["jpeg_podcast","jpegpodcast",0,0,0],
["josemurilo","Jose Murilo",0,0,0],
["HansTheGerman","Hans The German",0,0,0],
["TrallisInc","Trallis Inc",0,0,0],
["onelectriccars","onelectriccars",0,0,0],
["BallsOn_WallSt","Balls On Wall Street",0,0,0],
["DR12ZEB","Dr Zeb",0,0,0],
["brvandewalle","Bram Vandewalle",0,0,0],
["greyjay265","Grey Jabesi",0,0,0],
["Claudio8Rotunno","Claudio 🎱 Rotunno",0,0,0],
["stevebclarke","Steve Clarke",0,0,0],
["rafaelsantoni","Rafael Santoni",0,0,0],
["swixionary","Urban Krapf",0,0,0],
["AutoRoadcz","AutoRoad.cz",0,0,0],
["777_seven7","Studio Game",0,0,0],
["economistuacom","The Экономист",0,0,0],
["mralexreed","Alex Reed",0,0,0],
["M_the_Pro","henry@mthepro.com",0,0,0],
["itscedsworld","Ced Lordy I Hope",0,0,0],
["chris_howard_91","Christopher Howard",0,0,0],
["evworldeditor","EVWORLD.COM",0,0,0],
["MoeM3Power","Moє",0,0,0],
["MikelBilbao","Mike",0,0,0],
["BBDonze","Brad Donze",0,0,0],
["TristanTom","Tristan Tom",0,0,0],
["palSushobhan","SP",0,0,0],
["steve_watt1","Steve Watt",0,0,0],
["cleardiamondphx","cleardiamond",0,0,0],
["madengr","Louis Brown",0,0,0],
["2LUXURY2","2LUXURY2.com",0,0,0],
["DouglasHoltzman","Douglas Holtzman",0,0,0],
["steverose84","Steve Rose",0,0,0],
["DmitryLoki","Dmitry Loki",0,0,0],
["montimood","Mario Montag",0,0,0],
["mayankss","Mayank Saxena",0,0,0],
["gordianhense","gordian hense",0,0,0],
["ayirpelle","priya joseph",0,0,0],
["mrkylefield","Kyle Field",0,0,0],
["World_Weekly","The World Weekly",0,0,0],
["ed_roche","Edward Roche",0,0,0],
["ArielCinii","Ariel Cinii",0,0,0],
["ThucydidesOfUSA","Thucydides",0,0,0],
["trenddokument","trenddokument",0,0,0],
["MccauleyJay","jay b mccauley",0,0,0],
["rjquindoza","Rj Quindoza",0,0,0],
["pisalaam","Phillip Salaam",0,0,0],
["StockQuotes_Now","StockQuotes_Now",0,0,0],
["filotas","beyzad",0,0,0],
["SolarstromSimon","Solarstrom-Simon",0,0,0],
["QuezX_Bytes","QuezX Bytes",0,0,0],
["indianautos","Indian Autos Blog",0,0,0],
["lumenlord","Dorothea Braune",0,0,0],
["autocareersguru","Auto Careers Group",0,0,0],
["ApacheMXNetz","Saga Mina Mondy",0,0,0],
["TheNovelJuggler","Dana Smith",0,0,0],
["bracaza","Benedict Racaza",0,0,0],
["HiGarethDavies","Gareth Davies",0,0,0],
["Mittersinker","Gregor Mittersinker",0,0,0],
["MMorganOakes","Melissa Morgan-Oakes",0,0,0],
["Eseclavo",".:Lord Loco:.",0,0,0],
["BrendaHotmess","BrendaHotmessLarsen",0,0,0],
["Gerben015","Gerben",0,0,0],
["JPodzilla","John_Podlasek",0,0,0],
["RuchOpornikow","Ruch Oporników",0,0,0],
["AdamStewartFilm","Adam H Stewart",0,0,0],
["lazarodev","Fernando Lazaro",0,0,0],
["julienbrassine","Julien Brassine",0,0,0],
["adamoll18","Adam",0,0,0],
["profferedapp","Proffered Inc.",0,0,0],
["mihneastoian","Mihnea Stoian",0,0,0],
["TheSerkanY","AKıl ALmaz İŞLer!!!",0,0,0],
["leersumvanr","Ron van Leersum",0,0,0],
["kesabsy","Diran Afarian",0,0,0],
["go2mycloudcouk","go2mycloud",0,0,0],
["jriswick","James Riswick",0,0,0],
["eBayToHouse","DRG",0,0,0],
["Shawn__Berry","Shawn Berry",0,0,0],
["ylefeuvre","Yo",0,0,0],
["kelvinlim","kelvinlim",0,0,0],
["BuurautoNL","BuurautoNL",0,0,0],
["PerformGreen","Perform Green",0,0,0],
["TheQult","Matteo Fabbri",0,0,0],
["SmartThingsAuth","SmartThingsAuthority",0,0,0],
["trakin","Trak.in",0,0,0],
["MirzaMB","Mirza Mushtaq Baig",0,0,0],
["KurtHomes","Kurt Davidson Homes",0,0,0],
["agarwalm","Manish Agarwal",0,0,0],
["DarkayaDesigns","Darkaya Designs",0,0,0],
["graytesla","graytesla",0,0,0],
["joansilbo","Joan SB",0,0,0],
["brainy5s","Brainy Tech",0,0,0],
["mica_history07","Mica",0,0,0],
["AmineTX","Amine",0,0,0],
["DerpMcDergal","Derp McDergal",0,0,0],
["willevanparker","Will Parker",0,0,0],
["DodajGasMK","DodajGas MK",0,0,0],
["Auto_3","Auto",0,0,0],
["Zorriz0","Zorrizo",0,0,0],
["jarodlkp","jarodlkp",0,0,0],
["LewisMarshall","Lewis Marshall",0,0,0],
["JCardosoTW","JCardoso",0,0,0],
["iLevelSports","iLevelSportsNetwork",0,0,0],
["MistrTab","MrTab",0,0,0],
["dagherrmansour","Mansour Bou Dagher",0,0,0],
["CarlaxyS5","CarlaxyS5",0,0,0],
["manforathat","Doug Kinloch",0,0,0],
["imaginethis247","Imagine This",0,0,0],
["MassimoMagliari","Massimo Magliari",0,0,0],
["raisiwardres191","Marshall Davis",0,0,0],
["theobesteman","Theo Besteman",0,0,0],
["romn8tr","Rome Strach",0,0,0],
["StuartMacintyre","stuart Macintyre",0,0,0],
["mnmdriving","Faisal Shafiq",0,0,0],
["RyanMacvoy","Ryan MacVoy",0,0,0],
["philjel1","Phil Jellett",0,0,0],
["mrddefranco","Dylan DeFranco",0,0,0],
["STRATOFORTRESS9","JUAN CARLOS PUENTE",0,0,0],
["ChadCiaravella","ChadCiaravella",0,0,0],
["WRoberts_1943","Bill Roberts",0,0,0],
["WrightWayPhoto","WrightWayPhotography",0,0,0],
["nagsenk","Nagsen",0,0,0],
["Adan__world","Ferragamo_Falcon",0,0,0],
["JAKawahara_CA","Julie Kawahara",0,0,0],
["gabrielbhh","Gabriel Ben Harosh",0,0,0],
["cristian_miuta","Cristian Miuta 🔋",0,0,0],
["Abantech1","Abantech",0,0,0],
["KAlHomoud","Khalid AlHomoud",0,0,0],
["vinodinbh","John Varghese",0,0,0],
["nowheelspin","DaViD ThoMpsoN",0,0,0],
["Future_Ethics","Daníel G. Daníelsson",0,0,0],
["IlianaSergeev","Iliana Sergeev",0,0,0],
["artistmonkey83","Yolanda Reyes",0,0,0],
["LuxJaye","Jaye~~Lux",0,0,0],
["siliconclimate","Silicon Climate",0,0,0],
["nevergutless","Greg Schuster",0,0,0],
["RTn_Ecocars","RTn #Ecocars",0,0,0],
["giancarloperlas","Giancarlo Perlas",0,0,0],
["robfreemanjr","Rob Freeman Jr",0,0,0],
["buddhajones8","Kim Jones",0,0,0],
["Zimshady9611","Brent zimmerman",0,0,0],
["Tesla_Talk","Chester Worthington",0,0,0],
["phabanso","Pedro Pablo Parra",0,0,0],
["andresvourakis","Andres Vourakis",0,0,0],
["3Tplus","3Tplus.co",0,0,0],
["milosparipovic","Milos",0,0,0],
["hhg2Tech","Hitch Hiker",0,0,0],
["RFCAmbrian","RFCAmbrian",0,0,0],
["bdnic11","RoBobby",0,0,0],
["PaulKAAIJK","KAAIJK Paul",0,0,0],
["HighTechJoe","Joe",0,0,0],
["tomfeddor","Tom Feddor",0,0,0],
["BrianBRadio","Brian Bailey",0,0,0],
["RealCr33pY","The Real Cr33pY",0,0,0],
["Tensa4","Juma Kevin",0,0,0],
["StefanBubeck","Stefan Bubeck",0,0,0],
["ecommerceshares","eCommerceshares",0,0,0],
["plsburh","Joe Ross",0,0,0],
["kayemlin","Kaye Lin",0,0,0],
["baa2200","Benjamin Andersen",0,0,0],
["sharanyanlk","Sharanyan Sharma",0,0,0],
["thorlindberger","Thorsten Lindberger",0,0,0],
["sokneo","S. Anton",0,0,0],
["cvillebetty","Better World Betty",0,0,0],
["marcg392","Marc W Gossage",0,0,0],
["respond2demand","Rakesh Sharma, Zyom",0,0,0],
["adb1146","Andrew Bartels",0,0,0],
["DumaGento","DUMA GENTO",0,0,0],
["sandeepntq","Sandeep Nath",0,0,0],
["smartransportME","SmarTransport Summit",0,0,0],
["JeffMatlor","SillyVirtueSignaling",0,0,0],
["Ladidairo","Ladi Dairo",0,0,0],
["GreenStartPoint","GREEN START POINT",0,0,0],
["EricSWalz","Eric Walz",0,0,0],
["GDNonline","Gulf Daily News",0,0,0],
["powerrelation","Mike Kollin",0,0,0],
["EMIS_News","EMIS",0,0,0],
["msaiyaff","Saiyaff Farouk",0,0,0],
["facemantweets","faceMan",0,0,0],
["levitd","(((Levi Tillemann)))",0,0,0],
["SQNagency","SQN | Sine Qua Non",0,0,0],
["CWilgenbusch","Craig Wilgenbusch",0,0,0],
["ToHelpUmove","Mitch Rolsky",0,0,0],
["GreenerDriving","Greener Driving",0,0,0],
["halfglassuk","Daniel Cunningham",0,0,0],
["vitostech","☕️ La Pause Tech 📱",0,0,0],
["omarfg77","Omar Flores-Guzman",0,0,0],
["EmiliaMachuca","Emilia Machuca",0,0,0],
["Raepak","Raepak",0,0,0],
["PresidentLucero","Edward Lucero",0,0,0],
["WallStForsale","WallSt.ForSale",0,0,0],
["BooksBanter","Books & Banter",0,0,0],
["SpaceWhaleCo","SpaceWhaleCo",0,0,0],
["AdamOneConcerts","Adam Dittrich",0,0,0],
["24k","Chris Rauschnot",0,0,0],
["markamedia","Mark A. Lowe",0,0,0],
["OpenSrcEvangel","jaghvi mehta",0,0,0],
["MatWrede","Mathias Wrede 🇪🇺",0,0,0],
["maxicep","MaxiCep",0,0,0],
["aapakari","Antti Aapakari",0,0,0],
["stlwebsitedev","stlwebdev",0,0,0],
["themodel3guy","The Model 3 Guy",0,0,0],
["syedkami70","Cyber Warrior",0,0,0],
["Twalz","Thomas Walz",0,0,0],
["ElecVehicleGuy","Electric Vehicle Guy",0,0,0],
["lemonti","Leo Montiel 🇻🇪",0,0,0],
["i_s_ishan_singh","ISHAN SINGH",0,0,0],
["Salva_Escudero","Salva Escudero",0,0,0],
["fmarin_ES","Fernando Marín",0,0,0],
["ramiaqil","Rami aqil",0,0,0],
["prabhdeep_geek","Prabhdeep",0,0,0],
["_giiorgio","♛ Giorgio Avalos♛",0,0,0],
["dizzytown","David Zeng",0,0,0],
["Matthewgeise","Matt Geise",0,0,0],
["raventekinc","RavenTek, Inc",0,0,0],
["HusseinDia","Hussein Dia",0,0,0],
["Jannellynne","Jannelle Meade",0,0,0],
["davids7683","Charlie",0,0,0],
["caroenmike","Mike",0,0,0],
["Niclacoste","Niclacoste ⁶𓅓",0,0,0],
["BhargaviArun","Bhargavi",0,0,0],
["wearspacewear","wear",0,0,0],
["PiersBrown","Piers Brown",0,0,0],
["Techatic","Luke",0,0,0],
["lfcohen","Leonardo Cohen",0,0,0],
["smartearthling","Smart Earthling",0,0,0],
["electric_road17","Electric-Road",0,0,0],
["LexSelfMadeLife","Lex SelfMade Life",0,0,0],
["toncop","Tony Coppola",0,0,0],
["Path_Trading","PathTradingPartners",0,0,0],
["So_John","John",0,0,0],
["JonDSa","Jonathan D'Sa 🇨🇦",0,0,0],
["ayushtweet","Ayush Jain",0,0,0],
["ReimenH","Reimen Hii",0,0,0],
["PatrickSeelbach","Patrick Seelbach",0,0,0],
["Riskobe","♔вяyαη™",0,0,0],
["mdfbocarealtor","michael friedman",0,0,0],
["MagBordeaux2018","Mag Classine",0,0,0],
["wesSE22020","Wes",0,0,0],
["WaliaMandeep","Mandeep Walia 🇮🇳",0,0,0],
["thekevmaster","thekevmaster",0,0,0],
["MarketingVM","MarketingVoiceMail",0,0,0],
["campeaux","Brandon Брандон 🌹",0,0,0],
["vickisnemeth","Vicki S Nemeth",0,0,0],
["Uneeb_P","Uneeb Parkar",0,0,0],
["cherylferraro","Cheryl Ferraro",0,0,0],
["whatauto","whatauto.expert",0,0,0],
["HallEarle","Earle G Hall",0,0,0],
["carsinfopro","Cars Informations",0,0,0],
["prateekmgm","Prateek Saxena",0,0,0],
["OffDutyNinja","Kira Anne Peavley",0,0,0],
["NelsonRochaNYC","Nelson Rocha",0,0,0],
["MFAlliance","Jean McCluskey,P.E.",0,0,0],
["KenJayHaley","Ken J Haley",0,0,0],
["jwymangeek","J Wyman",0,0,0],
["Sakthi_Nava","Sakthi",0,0,0],
["qn215","Quan Nguyen",0,0,0],
["BenWongAsaoka","Benjamin Wong-Asaoka",0,0,0],
["twrpointwealth","Towerpoint Wealth",0,0,0],
["marketintelrpt","Market Intel Reports",0,0,0],
["TheUpgradeSale","ShiftMarketingStudio",0,0,0],
["TeslaSawFuture","TeslaSawFuture",0,0,0],
["cryolovemarin","Dalton Schuster",0,0,0],
["metaculus","Metaculus",0,0,0],
["macfixer_1","Brian Rothschild",0,0,0],
["bubbajenjen","Jenny",0,0,0],
["bhuvimore","Bhuvi More",0,0,0],
["stevegerritsen","Steve Gerritsen",0,0,0],
["AlexeyRev","ТыжФотограф",0,0,0],
["ev_tesla","Marc Baier",0,0,0],
["CleanOEnergy","♻CleanOceanEnergy♻",0,0,0],
["seedebtrun","See Debt Run",0,0,0],
["johnnbarth","John Barth",0,0,0],
["sk__671","SK",0,0,0],
["brookemelissa1","Brooke Walter",0,0,0],
["RajExpressNews","Raj Express",0,0,0],
["TSTEnergy","TheStreet Energy",0,0,0],
["BiotechMoney18","PrecisionTrade365",0,0,0],
["SinghfromUk","1SinghfromUK",0,0,0],
["Comp_Wheel","Competition Wheel",0,0,0],
["SuperCh29925216","SuperCharger",0,0,0],
["shaunakbangale","Shaunak Bangale",0,0,0],
["sunilshah39","Sunil",0,0,0],
["tiniskwerl","tiniskwerl",0,0,0],
["FrostSignsLtd","Frost Signs",0,0,0],
["LuxeRadio","Luxe Radio",0,0,0],
["RoyMathur","The Captain!",0,0,0],
["El_Deano","Dean Kawamura",0,0,0],
["MagneClip","Lucy A Mitchell",0,0,0],
["Zireal","Löwe mit Herz",0,0,0],
["TheJCSuperstar","Jonathan Cheng",0,0,0],
["mdabdussalam","Abdus Salam Mondal",0,0,0],
["southlivenews","South Live",0,0,0],
["corne06946803","corne du preez",0,0,0],
["Haramdar","AdamH",0,0,0],
["ravip0711","Ravi Patel",0,0,0],
["DomHennequin","Dom Hennequin",0,0,0],
["CohresLtd","Cohres Ltd.",0,0,0],
["lyndonward","Lyndon Ward",0,0,0],
["lancemace","Lance Mace",0,0,0],
["lairddoman","Laird Doman",0,0,0],
["berenyizs","Berényi Zsolt",0,0,0],
["SamSumbab","££LADYFLOWER84$$",0,0,0],
["ALTAS_PRESIONES","Anticiclón",0,0,0],
["FOTOISO3200","fi3200/EricSoucy",0,0,0],
["Ithinuel","Wilfried Chauveau",0,0,0],
["CollectivePitch","Brett K",0,0,0],
["WPKent","William Pierce Kent",0,0,0],
["zephyrzap","Adnan Ariffin",0,0,0],
["3DPLab","threeDP",0,0,0],
["omarvaid","Omar Vaid",0,0,0],
["bethbuczynski","Beth Buczynski",0,0,0],
["ileong","Ian Leong",0,0,0],
["FilmFanRant","Film Fan Rant",0,0,0],
["fox66","Baron Basil Brush",0,0,0],
["Drunkenclod","Tomas Krynsky",0,0,0],
["d_realcharles","charles hyacinth",0,0,0],
["leesonsteve","Steve Leeson",0,0,0],
["xaBacacha","Javier",0,0,0],
["solebalduzzi","Soledad Balduzzi F.",0,0,0],
["stuv1k","stuv1k",0,0,0],
["MothInnovate","Moth ~ Innovate",0,0,0],
["evopinion","EV Opinion",0,0,0],
["themoken","Jack Miller",0,0,0],
["imlauraramos","Laura Ramos",0,0,0],
["Balance_Recruit","Balance Recruitment",0,0,0],
["Gage_T_Foley","Gage T Foley",0,0,0],
["INESSOFTZA","INESSOFT",0,0,0],
["domgaleon","Dominic John Galeon",0,0,0],
["michael_boggia","Michael Boggia",0,0,0],
["GameChange101","Game Changer 101",0,0,0],
["RV_TechEd","Mr. Robby Jacobson",0,0,0],
["pixelconscient","Pixel Conscient",0,0,0],
["AutoIES","Auto-IES.com",0,0,0],
["its_pu","🖤♥✞Pᴜᴊᴀ D✞♥🖤",0,0,0],
["stephanedeluca","Apple Tree Mag (SDL)",0,0,0],
["autelectrico","AUTELEC",0,0,0],
["ks7000","ks7000.net.ve 💾",0,0,0],
["exworld3","eXWorld Tech News",0,0,0],
["YovanaAcuna","Yovana Acuña",0,0,0],
["f_lozada95","big frank",0,0,0],
["newsmagz_net","newsmagz.net",0,0,0],
["Gattina721","Sabina_Gattina72",0,0,0],
["SMotovlog","Steve´s Motovlog",0,0,0],
["CorinneKuehne","Corinne Kühne",0,0,0],
["30dB","30dB",0,0,0],
["McMcbillion43","McBillion",0,0,0],
["CodeyBleu","Dakota Bomar",0,0,0],
["infotvca","InfoTV Canada",0,0,0],
["NBDPress","National Biz Daily",0,0,0],
["thepacifist89","everglades",0,0,0],
["foresight_lab","Klaus Burmeister",0,0,0],
["__timreynolds","Tim Reynolds",0,0,0],
["iruizpatallo","Iván Ruiz Patallo",0,0,0],
["danthedoozy","Daniel K. Driskill",0,0,0],
["Poppy_5mith","Poppy Smith",0,0,0],
["DemonJim","DemonJim",0,0,0],
["ZroHour","SummerStormHour(Jon)",0,0,0],
["TheCarAddict","Lisa TheCarAddict",0,0,0],
["GibbsBlake","Blake Gibbs",0,0,0],
["Lori8lingerG","Lori Ettlinger Gross",0,0,0],
["myvipguy","Jason McCormac",0,0,0],
["EJMun","Eduardo Javier Muñoz",0,0,0],
["_neurozone","N-euro-zone🌍",0,0,0],
["reviewmediatv","iam_bobbyv",0,0,0],
["Cisco_Mobile","Todd Smith",0,0,0],
["33_Entrepreneur","ed",0,0,0],
["otolifee","oto.life",0,0,0],
["William42Vs","WilliamV Vysniauskas",0,0,0],
["Cicciglio","Marco Dessì",0,0,0],
["MouliVeleti","Mouli",0,0,0],
["BaruchProForum","BaruchProForum",0,0,0],
["kingumar91","Umar Raja",0,0,0],
["gana_energia","Gana Energía",0,0,0],
["MarkkuHusso","Markku Husso",0,0,0],
["AUTOundMOTORS","AUTO-und-MOTORS.de",0,0,0],
["model_tesla","Tesla Model",0,0,0],
["ruhtyt","Ruth",0,0,0],
["channingdutton","Channing Dutton",0,0,0],
["utopian_digital","Utopian Digital",0,0,0],
["cedricdubree","Cedric Dubree",0,0,0],
["eganschulz","Egan Schulz",0,0,0],
["missjoycevega","Joyce Vega",0,0,0],
["Techn_o_world","TechnoWorld India",0,0,0],
["sixoh60","Roger Crawford",0,0,0],
["bittersweet9","Lisa Paternella",0,0,0],
["pm83online","Phil Martin",0,0,0],
["mdierker","Markus Dierker",0,0,0],
["Masse_","Max Angelma",0,0,0],
["ActuAutoFR","Actu Auto FR",0,0,0],
["Ramani_Iyer","N Ramani Iyer",0,0,0],
["BayleyB_97","Bayyb🦁",0,0,0],
["MsRedTigress","Robyn Barfoot",0,0,0],
["ClaireGapais","Claire GAPAIS",0,0,0],
["deniselange","Denise Lange",0,0,0],
["TheChappst3r","sean chappell",0,0,0],
["California_b","Bridget Tyler",0,0,0],
["TheBigGreenCo","TheBigGreenCompany",0,0,0],
["FManagementMtdR","FacilityManagentMtdR",0,0,0],
["cpaUCSB","James Brady",0,0,0],
["sknib","Jack",0,0,0],
["RogerBohn","Roger Bohn",0,0,0],
["HealthWealthZW","Lemuel",0,0,0],
["thanqu0l","Bernt Granbacke",0,0,0],
["jsifu","Juan  Sifuentes",0,0,0],
["plassmag","plassma",0,0,0],
["MrTechInc","Mr. Tech, Inc",0,0,0],
["eleccaradvice","EVA",0,0,0],
["etalors1","Tina Tang",0,0,0],
["jameel_jackson","Jameel Jackson",0,0,0],
["mantaray1990","Storm Ikin",0,0,0],
["LnjExhibits","LNJ Exhibits",0,0,0],
["BizVibeHQ","BizVibe",0,0,0],
["MACROPOLISMCMXV","Marcus Cooper",0,0,0],
["jaytheredneck1","Jay",0,0,0],
["haarusso","Louis",0,0,0],
["drjeff_unb","Dr. Jeff McNally",0,0,0],
["Edelsway","Edelsway",0,0,0],
["HTeezar","X",0,0,0],
["xcvmanman","MAMAN",0,0,0],
["NeloMarial","BenMarial",0,0,0],
["FlaviusHarabor","Flavius Harabor",0,0,0],
["simlink_it","simlink",0,0,0],
["new_markets","Karthik Ramani",0,0,0],
["W_W_F","WENDY W FOK 🐼",0,0,0],
["zesty_tech","Zesty Tech News",0,0,0],
["JulioEscribano","Julio Escribano",0,0,0],
["m2mworld","IoT World",0,0,0],
["Marc_van_Dijck","Marc van Dijck",0,0,0],
["YorshMarti","Yorsh Martī",0,0,0],
["windlord03","Windlord",0,0,0],
["kiko1213","Enrique T.",0,0,0],
["ElectricRacer87","Me",0,0,0],
["learntesla","Learn Tesla",0,0,0],
["RVerrengia","robertoverrengia",0,0,0],
["hometecsarl","HOMETEC",0,0,0],
["lerato_motau","iLove",0,0,0],
["KKRSeattle","Kristian K Rickard",0,0,0],
["Fin24_Tech","@Fin24Tech",0,0,0],
["chrishendel","Chris Hendel",0,0,0],
["KkyyoKotome","楊豐銘",0,0,0],
["XRIM","XRIM Money",0,0,0],
["0l1l2","Chealsea",0,0,0],
["imLwi","Louis Dickinson",0,0,0],
["updayDE","upday for Samsung DE",0,0,0],
["RichHargrave","Rich Hargrave",0,0,0],
["GNT_fr","Génération-NT",0,0,0],
["brendamaiy","Brenda",0,0,0],
["libarsa","L.Mauro!",0,0,0],
["techsectorguy","That Tech Sector Guy",0,0,0],
["Madodel1","Mark Dodel",0,0,0],
["ZoomInKorea","Korea_Insight",0,0,0],
["nunione_","Эйнштейн",0,0,0],
["highrgrndsocial","Higher Ground Social",0,0,0],
["protopet","Zach",0,0,0],
["illmaticwes81","Wes",0,0,0],
["gameshowevent","Game Show Event",0,0,0],
["JediJer","Jeremy Hoskins",0,0,0],
["botberger","botberger",0,0,0],
["PablodelaMac","P.delaMacorra Canals",0,0,0],
["FredZ_DK","FredZ",0,0,0],
["themaddiary","Southern Barbarian",0,0,0],
["ICT_GURU","AJ Kulatunga",0,0,0],
["jorgeluisrudo","Jorge Luis",0,0,0],
["frankk47","frank corallo",0,0,0],
["snkutty81","Sankar",0,0,0],
["elsworthanthony","Elsworth Anthony",0,0,0],
["relationequity","ruth sandoval",0,0,0],
["AJLicata","Anthony Licata",0,0,0],
["dvizhokmag","Журнал Движок",0,0,0],
["nisharotech","Nishant Arora",0,0,0],
["green_fanatics","Green Fanatics",0,0,0],
["mohammad_na3eem","Na3eem",0,0,0],
["shruthi4891","Shruti Shetty",0,0,0],
["hope_74","Thumay",0,0,0],
["panostore75","panostore75",0,0,0],
["waverunninggeek","waverunning.geek",0,0,0],
["DPypczynski","Dariusz Pypczynski",0,0,0],
["IDigitalTrend","iDigital Trends",0,0,0],
["_Cazador_","C4z4d0r D. C4nt1",0,0,0],
["carlosgil12ve","Carlos Eduardo Vivas",0,0,0],
["sanvai","santhanam",0,0,0],
["kaptfigo","Gordon Becker",0,0,0],
["ShawnHymel","Shawn Hymel",0,0,0],
["DrewCasper","Drew Casper",0,0,0],
["KplaygroundInc","Kplayground",0,0,0],
["roblamastus","Robert LaMastus",0,0,0],
["OndrewH","OnDrew Hartigan",0,0,0],
["JoshJack","at Josh Jack",0,0,0],
["GreenerTalk","AbbaShayan",0,0,0],
["TheTeslaModel3","TeslaModel3",0,0,0],
["Doctor_Mjay","Mathanee Perez-Ortiz",0,0,0],
["corpomir","КорпоМИР",0,0,0],
["kaa_pain66","kayvon",0,0,0],
["Freddies_Corner","Freddies Corner",0,0,0],
["PSWillemsen","Paul Willemsen",0,0,0],
["effgov","EfficientGov",0,0,0],
["thalyarae","natalie r k mccarthy",0,0,0],
["SvetmobilneCZ","Svetmobilne.cz",0,0,0],
["TripleForged","TripleForged",0,0,0],
["Cybroze","Cybroze Official",0,0,0],
["KirakFirangi","Kirak Firangi",0,0,0],
["RAULITObdn","Raul",0,0,0],
["KEZAKOTO","KEZAKOTO",0,0,0],
["tahab621","Taha",0,0,0],
["TMN_Online","Inno Media",0,0,0],
["ManojdevaY","Manoj Deva",0,0,0],
["TheWebAfter","Web After Tomorrow",0,0,0],
["oznerol93","Lorenzo Spada",0,0,0],
["jckronbauer","Julio Kronbauer",0,0,0],
["mbarone557","Mike Raga-Barone",0,0,0],
["iam_Sudip","Sudip",0,0,0],
["AutoExtrem","AutoExtrem",0,0,0],
["Bruce_where","Bruce de Beer",0,0,0],
["AbacusNYC","Abacus Entertainment",0,0,0],
["Firmenhistorik","Harald Binder",0,0,0],
["Olkurola","Olavi Kurola",0,0,0],
["sgo46","Sanjiv Gossain",0,0,0],
["PramodIndunith","Pramod Indunith",0,0,0],
["MarraBeppe","Beppe Marra",0,0,0],
["DeAfMaCbOi","DeAfMaCbOi",0,0,0],
["SpartanLineage","Dienekes",0,0,0],
["automoviles","automoviles",0,0,0],
["iHimanshuHK","Himanshu",0,0,0],
["OldSchoolDonzi","Robert Anthony Brown",0,0,0],
["imthehostshow","I'm the Host",0,0,0],
["mathrubhumi","Mathrubhumi",0,0,0],
["AlainTimmers","Alain Timmers",0,0,0],
["madusupun","Màӽìɱům Ćĥåɱøď™",0,0,0],
["klixba","Klix.ba",0,0,0],
["gthiell","Grégory Thiell",0,0,0],
["nickhajicosti","Nick Hc",0,0,0],
["victorcab","Victor Caballero",0,0,0],
["amichaelevansjr","A Michael Evans Jr",0,0,0],
["roland_bieri","Roland Bieri",0,0,0],
["bapechun","Eric Keung",0,0,0],
["StayingFastLane","Taylor Running",0,0,0],
["eliseomartelli","Eliseo Martelli",0,0,0],
["delpasand88","Del Pasand",0,0,0],
["Styn_Mertens","Stijn Mertens",0,0,0],
["AngelieGutib","angelie gutib",0,0,0],
["Esist_Me","ESIST",0,0,0],
["plafford","plafford",0,0,0],
["stuckonHX","entrepreneur@Heart",0,0,0],
["MTurner_IRL","Matthew Turner",0,0,0],
["555ft","Bob Loblaw",0,0,0],
["simpletechman","Tech Simplified",0,0,0],
["Lord_Bonnie","Lord Bonnie",0,0,0],
["JSWolfwood","Jeremiah Wolfwood",0,0,0],
["elonliveAT","e l o n",0,0,0],
["GreeneParsons","Laura Greene Parsons",0,0,0],
["sebastiande19","Sebastian De Long",0,0,0],
["MotorVision_","Motor-Vision",0,0,0],
["A_R_Goldberg","Andrew Goldberg",0,0,0],
["matchbkr","Matchbkr Inc",0,0,0],
["Myownvoice79","DIANAETERNO111111111",0,0,0],
["vishnu_narang","Vishnu Narang",0,0,0],
["ludmilda_i","Ludmila",0,0,0],
["Wordforce","Bill Clayton",0,0,0],
["HAJunaidi","Haroon Junaidi",0,0,0],
["udaytendulkar","uday",0,0,0],
["allenlenon","PatrickAllen Cortado",0,0,0],
["Nate_Fisher_79","Nathaniel Fisher",0,0,0],
["rawveganblkgirl","Kisha Mattox",0,0,0],
["IotaRun","Fran Cortez",0,0,0],
["ParkingReview","Parking Review",0,0,0],
["GoldenCapital1","Drew Golden",0,0,0],
["ahsanfp","Ahsan Nadeem",0,0,0],
["TheWorldCrisis","The World in Crisis",0,0,0],
["lui5jacint0","Lui5 Jacint0",0,0,0],
["_Its_Ralph","Ralph",0,0,0],
["0Technorama","Technorama",0,0,0],
["SPECTREapparel","SPECTRE APPAREL",0,0,0],
["tckilla36","Tom",0,0,0],
["edutechie","Jeff VanDrimmelen",0,0,0],
["Spacewolf_1","Patelout Benoit",0,0,0],
["dobbersp","dobber",0,0,0],
["CarBuyingGuides","CarBuyingStrategies",0,0,0],
["yaelol","yaelol",0,0,0],
["Acuchi","acuchi",0,0,0],
["elnar_akov","Elnar Akov",0,0,0],
["Charlieperg","Carlos Pérez",0,0,0],
["ReinhardSA","Reinhard FraKe 🇿🇦",0,0,0],
["NewsOnScreen","News On Screen",0,0,0],
["utahpublicradio","Utah Public Radio",0,0,0],
["Plitvica","ValentinaJanjus",0,0,0],
["MillennianMag","Millennian",0,0,0],
["rubenlpgamer","×Lost Phantom Gamer×",0,0,0],
["algeol","IG: leisla",0,0,0],
["BestAuto007","Best Auto",0,0,0],
["theteslife","theteslife",0,0,0],
["lalitpatkiMT","Lalit S Patki",0,0,0],
["OLoingsigh","Eoin O'Loingsigh",0,0,0],
["mussocpa","Mussocpa.net",0,0,0],
["IETEF","DJ CaveM",0,0,0],
["GGattr","Gabriel",0,0,0],
["hitech_guru","Sandeep Shenoy",0,0,0],
["raultorres2000","Raul Torres",0,0,0],
["paulalexanderf1","paul alexander",0,0,0],
["ManiManiraju13","Mani Raj",0,0,0],
["ukr_media","Ukr.Media",0,0,0],
["Khaled_M_K","Khaled",0,0,0],
["adie_pie","Adie Pie",0,0,0],
["McCrunkle","McCrunkle",0,0,0],
["Tuviae","Tuvia Elbaum",0,0,0],
["sickchipkits","S.I.C.K Chip Kits",0,0,0],
["DriverlessRev","DriverlessRevolution",0,0,0],
["BlairTraveler","Blair Gardner",0,0,0],
["jqontech","John Quain",0,0,0],
["RJClarksonc","Richard J. Clarkson",0,0,0],
["AcK_c_u","Attilio Burroni",0,0,0],
["Bertino311","Dan Bertino",0,0,0],
["urfrn4ever","Rohit Gupta",0,0,0],
["neurotech1","John Ellis",0,0,0],
["allie_mhr","Allie M",0,0,0],
["Mariscal_MX","E. Mariscal",0,0,0],
["ShaveTank","ShaveTank",0,0,0],
["Optimumeurope","Optimum Car Care",0,0,0],
["stitah","« s t e f »",0,0,0],
["WEBUREcom","WEBURE",0,0,0],
["The_FaizanAhmad","Faizan Ahmad",0,0,0],
["tem_psikhopat","Tem Psikhopat",0,0,0],
["jeffreymathews","Jeff Mathews",0,0,0],
["RaymondAMeijer","Raymond",0,0,0],
["CarolinaSeaGal","SeaView",0,0,0],
["empower_elec","empower electricity",0,0,0],
["AmBlacktop","AmericanBlacktop",0,0,0],
["intaucom","INT News & Trends",0,0,0],
["AleMaestroni","Alessandro",0,0,0],
["SarahSturtevant","Sarah Sturtevant",0,0,0],
["IHTWealth","IHT Wealth",0,0,0],
["value4valuables","Roberto Sabatino",0,0,0],
["tomkenis","Tom Kenis",0,0,0],
["Lux_Cipolletta","Lucio Cipolletta",0,0,0],
["r33bit","☁☁Peter☁☁",0,0,0],
["flyboy_troy","Troy",0,0,0],
["digital_trav","Digital-Traveler",0,0,0],
["AdrianIchim09","Adrian Ichim",0,0,0],
["DanVuch","Dan Vuchenich",0,0,0],
["gbejic","Gabrijel Bejić",0,0,0],
["Municipal_Bank","Banco Municipal",0,0,0],
["RoeliganNL","Roel van der Hoeven",0,0,0],
["LTNutrition","Leah Tarleton",0,0,0],
["smithymayo","Mayo",0,0,0],
["MaxMaxcolin4","Max Colin",0,0,0],
["HimGoJourno","Himanshu Goenka",0,0,0],
["IoannisBreier","Ioannis Breier",0,0,0],
["kaemizzo","Michael Schunke",0,0,0],
["yesnoyess","FJ",0,0,0],
["kbansink","Katherina B Ansink",0,0,0],
["ElectrikOne","Beefer Sutherland ❄️",0,0,0],
["Pia_ECHELON","Pia Richter",0,0,0],
["EnergyResDigest","E&R Digest",0,0,0],
["PaulinaMura","Paulina Mura",0,0,0],
["Cazana","Cazana",0,0,0],
["JoyceLaPlant","Joyce La Plante",0,0,0],
["Lies_Roofer","Liesbeth",0,0,0],
["ChinaGregory","Gregory Mark Hill",0,0,0],
["CColon_WFG","Christopher Colón",0,0,0],
["ricmarfi","Riccardo Marchiani",0,0,0],
["CAgerbo","Claus Agerbo",0,0,0],
["Taillefira","P R TAYLOR, Inc.",0,0,0],
["C_Desir","Calvyn Desir",0,0,0],
["RichardGledhill","Richard Gledhill",0,0,0],
["PHCNetworks","PHCNetworks",0,0,0],
["surajbalchand","Suraj Balchand",0,0,0],
["DanHuegli","Daniel Hügli",0,0,0],
["faith6357","Rakesh Mehta",0,0,0],
["G33PERS","Geepers",0,0,0],
["dylandawson2","Dylan Dawson",0,0,0],
["andrewNfarrens","Andrew N. Farrens",0,0,0],
["AlphaReboot","Nick H",0,0,0],
["JorgeIII","Jorge",0,0,0],
["Hin3512","Amazing_handsome_boy",0,0,0],
["sa3dan","G. Sa3dan",0,0,0],
["TruckerAsian","AsianTrucker",0,0,0],
["WendiiiE","Wendy Lee",0,0,0],
["james_gravity","James Strieb",0,0,0],
["CarNewsBit","Top Car News",0,0,0],
["nikiwaibel","Niki Waibel",0,0,0],
["chiradio","ChiRadio",0,0,0],
["enginer285","Mariusz Majchrzak",0,0,0],
["dobrien80","Dan O'Brien",0,0,0],
["scottf6f","Scott M.",0,0,0],
["velocitysnare","Dustin Tanner",0,0,0],
["JSiminoski","James Siminoski",0,0,0],
["_a2ps","Aditya Patil",0,0,0],
["detansinn","Det Ansinn 👨‍💻",0,0,0],
["longhorncomfort","Toni Ryerson Comfort",0,0,0],
["nicyantzi","Nic Yantzi",0,0,0],
["rolecondena","Robin Ideker",0,0,0],
["mtvhotbend","Ben Yap",0,0,0],
["Duped_2016","~°Duped_2016°¬",0,0,0],
["sheldonnogeek","M. Crutchfield",0,0,0],
["MarathonOfLight","Marathon of Light",0,0,0],
["Orfanidns","Vassilis Orfanidns",0,0,0],
["Reload_Spain","Pau",0,0,0],
["_j3ffrey","Jeff Anderson",0,0,0],
["prxagentur","PRX",0,0,0],
["FinInvTr","FinInvTr",0,0,0],
["1SimplySimon","TheUberDriver™",0,0,0],
["InfinitusCap","Infinitus Capital",0,0,0],
["lasas","Vladas Lasas",0,0,0],
["ItsChrisShorts","@IAmChrisShorts",0,0,0],
["iZerreg","i Zerreg",0,0,0],
["GoEcoLogic","Eco♻️Logic",0,0,0],
["Ivyleague34","Ms. White",0,0,0],
["Tagisade","Oliver Tagisade",0,0,0],
["andre_mundo","André Mundo",0,0,0],
["CarsDirect","CarsDirect",0,0,0],
["eighth_samurai","Niteen Bali",0,0,0],
["nTangledCloud","nTangled Cloud",0,0,0],
["TrendinTech","TrendinTech",0,0,0],
["Gregordreams","Gregor",0,0,0],
["jose_rabadan","Jose Manuel Rabadán",0,0,0],
["MindsEyeShow","Mind's Eye Podcast",0,0,0],
["O2L","O2L",0,0,0],
["a_dree_en","Adrienne Fidelino",0,0,0],
["UncloudedVision","Gabriel Henton",0,0,0],
["Iliadis_Ioannis","Ioannis Iliadis",0,0,0],
["VR_BHart","Brian Hart",0,0,0],
["nageshpolu","nageshpolu",0,0,0],
["ElFiscalGodot","ElFiscalGodot",0,0,0],
["DrawnSolutions","Drawn Solutions",0,0,0],
["newauto2017","New Auto",0,0,0],
["amoelcordero","SarMychael",0,0,0],
["zsibritajanos","Janos Zsibrita",0,0,0],
["VPajkovski","Vladimir Pajkovski",0,0,0],
["doradoz423","Not You",0,0,0],
["LeverageTG","Leverage Technology",0,0,0],
["RavngBlueDevil","Blue",0,0,0],
["RobertSelzler","Robert Selzler",0,0,0],
["HBuxant","Henry Buxant",0,0,0],
["tweetARTech","Aymaan Rahman",0,0,0],
["wilklasu","Jarek Luczak",0,0,0],
["Autocarvid","Autocatvid",0,0,0],
["peterJwouda","Peter Wouda",0,0,0],
["MarkusJonesWins","Markus Jones",0,0,0],
["latenite2016","LATE NITE",0,0,0],
["Fillsout","Lucky™",0,0,0],
["johnlewinski","John Scott Lewinski",0,0,0],
["StephanLangenau","Stephan",0,0,0],
["DeathConElite","Manny Munoz",0,0,0],
["sepaulsamson","Paul samson",0,0,0],
["luismp1970","Luis Montalbán Pozas",0,0,0],
["AutosAmBlog","AutosAméricainesBlog",0,0,0],
["Felnuba","Felipe Núñez Badínez",0,0,0],
["electronicspec","Electronic Specifier",0,0,0],
["teqnomad","teq nomad",0,0,0],
["gwhitackerc","Gregory Whitacker",0,0,0],
["ae_magazine","AutomobileEntreprise",0,0,0],
["nitinkumar1976","nitin kumar",0,0,0],
["priteshpalan","Pʀɪᴛᴇsʜ Pᴀʟᴀɴ",0,0,0],
["MiniMeMotors","Mini Me Motors",0,0,0],
["Scubadidas","Scuba James",0,0,0],
["stapf","stapf",0,0,0],
["TheWestsideNews","The Westside Story",0,0,0],
["MatjasicNick","Nick Matjasic",0,0,0],
["JMarcrako","Marc Rakoto-Lahy",0,0,0],
["GABhushanBabu","G.A.Bhushan Babu",0,0,0],
["idea2go","Paul Hess",0,0,0],
["Rikizimo","Riki Ð'Neri ♻",0,0,0],
["orsini70","Giancarlo Orsini",0,0,0],
["mortenrene","Morten René",0,0,0],
["SinoswissTitani","sino-swiss Titanium",0,0,0],
["_Darwen_","David Marco Tolosana",0,0,0],
["ZachZaborny","Zach Zaborny",0,0,0],
["DanBuk4","Daniel Buk",0,0,0],
["ShareUpp","ShareUpp",0,0,0],
["ayfchang9021","Andy Chang",0,0,0],
["TruePcKing","True Pc King",0,0,0],
["mylucky137276","My Lucky",0,0,0],
["ElectricVansUK","SEEVS EVs London",0,0,0],
["heyimjoew","Joe Wituschek 📎",0,0,0],
["teknoblog_ru","ТЭКНОБЛОГ",0,0,0],
["techtontro","Tech Tontro",0,0,0],
["patrick_herrity","Patrick Herrity",0,0,0],
["leziwok","Jérémie Le Guen",0,0,0],
["kmax_chicago","K Max",0,0,0],
["melvinology","Melvin Richard",0,0,0],
["RepsforGenius","Bree Of Tart",0,0,0],
["grsmith8","Epistulae140",0,0,0],
["gswcowboy","Ren",0,0,0],
["mkonkolowicz","Maciej Konkolowicz",0,0,0],
["en1am","m a r y n e",0,0,0],
["Topette35","Topette",0,0,0],
["mmarinmx","Mario Marin",0,0,0],
["JesusFraileArda","Jesus Fraile Ardanuy",0,0,0],
["fanautosUS","Francois Laroche",0,0,0],
["a5604138","璃音　緒（リオン　チョイ）",0,0,0],
["tibochardin","tibo.c",0,0,0],
["carangonu","Carlos Rafael Angón",0,0,0],
["martian_no13","🎃",0,0,0],
["thevishnunair","Vishnu Nair",0,0,0],
["SingleMind","SingleMind",0,0,0],
["yeahforeal","Derek Foreal",0,0,0],
["PatSnap","PatSnap",0,0,0],
["350Deschutes","350Deschutes",0,0,0],
["shobhit07","Shobhit Srivastava",0,0,0],
["ReinerHinz","Rainer",0,0,0],
["phershenson","Paul Hershenson",0,0,0],
["whitebettys","Betty W",0,0,0],
["ContiTonight","Conti Tonight Show",0,0,0],
["HOPE4THE_FUTURE","BIG AL",0,0,0],
["tinyhandedman","Darren Murray",0,0,0],
["RICHuals","My Richuals",0,0,0],
["MovilidadVerde","Movilidad Verde",0,0,0],
["JadeJadore","Jade J'adore",0,0,0],
["WilsonOrtiz","Wilson R. Ortiz",0,0,0],
["outz0n3d","out[z0n3d]",0,0,0],
["scrid_hb","Jon Dickinson",0,0,0],
["Kuipo","Kuipo",0,0,0],
["thanasiii","Thanasi Papoulias",0,0,0],
["TechNewsbit","Top Technology News",0,0,0]
];